/* Generated from diagrams.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
/* Audax OS site · diagrams
   Three signature visual moments:
   - MatrixDiagram  (5 spheres × 5 layers × 3 modes — isometric grid)
   - NestedCircles  (5 layers — concentric, individual at the core)
   - ModesTriad     (3 modes — human↔human, human↔agent, agent↔agent)

   All drawn in SVG using the brand palette. No external icons. */

/* ---------- Matrix : Spheres × Layers × Modes (equation) ---------- */
const MatrixDiagram = () => {
  const SX = [168, 500, 832],
    CROSS = [334, 666];
  const vizY = 222;
  const MONO = 'JetBrains Mono, monospace',
    SERIF = 'Instrument Serif, serif';

  // Spheres — five named circles in a pentagon
  const sphereNames = ['Value', 'Work', 'Relationship', 'Learning', 'Communication'];
  const sphereTint = ['#1F4D2E', '#2D6B41', '#3F8657', '#6BA37C', '#9CBFA3'];
  const scx = SX[0],
    scy = vizY + 10,
    sR = 50,
    sr = 24;
  const spts = sphereTint.map((_, i) => {
    const a = -Math.PI / 2 + i * 2 * Math.PI / 5;
    return [scx + sR * Math.cos(a), scy + sR * Math.sin(a), a];
  });

  // Layers — five equal isometric planes, vertically aligned
  const layerNames = ['Individual', 'Team', 'Organization', 'Family', 'Ecosystem'];
  const layerTint = ['#C8DBC9', '#E2EBDD', '#E2EBDD', '#F0F4EC', '#F0F4EC'];
  const lcx = 500,
    lcyBase = 314,
    lhw = 80,
    lvh = 27,
    ldy = 40;

  // Modes — three named interaction icons (human / agent)
  const modeRows = [vizY - 66, vizY + 2, vizY + 70];
  const modeKinds = [['h', 'h'], ['h', 'a'], ['a', 'a']];
  const modeLabels = ['HUMAN ↔ HUMAN', 'HUMAN ↔ AGENT', 'AGENT ↔ AGENT'];
  const mcx = SX[2],
    mdx = 40,
    ms = 1.05;
  const human = (cx, cy) => /*#__PURE__*/React.createElement("g", null, /*#__PURE__*/React.createElement("circle", {
    cx: cx,
    cy: cy - 7 * ms,
    r: 6 * ms,
    fill: "#1F4D2E"
  }), /*#__PURE__*/React.createElement("path", {
    d: `M ${cx - 11 * ms} ${cy + 11 * ms} a ${11 * ms} ${11 * ms} 0 0 1 ${22 * ms} 0 Z`,
    fill: "#1F4D2E"
  }));
  const agent = (cx, cy) => {
    const col = '#3F8657';
    return /*#__PURE__*/React.createElement("g", null, /*#__PURE__*/React.createElement("line", {
      x1: cx,
      y1: cy - 9 * ms,
      x2: cx,
      y2: cy - 15 * ms,
      stroke: col,
      strokeWidth: 1.6 * ms
    }), /*#__PURE__*/React.createElement("circle", {
      cx: cx,
      cy: cy - 16 * ms,
      r: 2.1 * ms,
      fill: col
    }), /*#__PURE__*/React.createElement("rect", {
      x: cx - 13 * ms,
      y: cy - 3 * ms,
      width: 3 * ms,
      height: 7 * ms,
      rx: 1.4 * ms,
      fill: col
    }), /*#__PURE__*/React.createElement("rect", {
      x: cx + 10 * ms,
      y: cy - 3 * ms,
      width: 3 * ms,
      height: 7 * ms,
      rx: 1.4 * ms,
      fill: col
    }), /*#__PURE__*/React.createElement("rect", {
      x: cx - 10 * ms,
      y: cy - 9 * ms,
      width: 20 * ms,
      height: 18 * ms,
      rx: 4.5 * ms,
      fill: col
    }), /*#__PURE__*/React.createElement("circle", {
      cx: cx - 4.5 * ms,
      cy: cy - 1.5 * ms,
      r: 2.2 * ms,
      fill: "#fff"
    }), /*#__PURE__*/React.createElement("circle", {
      cx: cx + 4.5 * ms,
      cy: cy - 1.5 * ms,
      r: 2.2 * ms,
      fill: "#fff"
    }), /*#__PURE__*/React.createElement("rect", {
      x: cx - 5 * ms,
      y: cy + 4 * ms,
      width: 10 * ms,
      height: 2 * ms,
      rx: 1 * ms,
      fill: "#fff"
    }));
  };
  const glyph = (k, cx, cy) => k === 'h' ? human(cx, cy) : agent(cx, cy);
  return /*#__PURE__*/React.createElement("div", {
    className: "diagram-axes"
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 1000 380",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Five spheres times five layers times three modes"
  }, SX.map((x, i) => /*#__PURE__*/React.createElement("text", {
    key: 'eq' + i,
    x: x,
    y: 64,
    fontFamily: SERIF,
    fontSize: "46",
    fill: "#0E2419",
    textAnchor: "middle"
  }, [5, 5, 3][i])), CROSS.map((x, i) => /*#__PURE__*/React.createElement("text", {
    key: 'cr' + i,
    x: x,
    y: 60,
    fontFamily: MONO,
    fontSize: "30",
    fill: "#C9C6BD",
    textAnchor: "middle"
  }, "\xD7")), ['SPHERES', 'LAYERS', 'MODES'].map((t, i) => /*#__PURE__*/React.createElement("text", {
    key: 'cap' + i,
    x: SX[i],
    y: 92,
    fontFamily: MONO,
    fontSize: "11",
    fill: "#807D72",
    letterSpacing: "0.18em",
    textAnchor: "middle"
  }, t)), /*#__PURE__*/React.createElement("polygon", {
    points: spts.map(p => p[0] + ',' + p[1]).join(' '),
    fill: "none",
    stroke: "#9CBFA3",
    strokeWidth: "1",
    opacity: "0.5"
  }), spts.map((p, i) => /*#__PURE__*/React.createElement("circle", {
    key: 'sc' + i,
    cx: p[0],
    cy: p[1],
    r: sr,
    fill: sphereTint[i],
    opacity: "0.95"
  })), spts.map((p, i) => {
    const dx = Math.cos(p[2]),
      dy = Math.sin(p[2]);
    const lx = scx + (sR + sr + 7) * dx,
      ly = scy + (sR + sr + 7) * dy + 3;
    const anchor = dx > 0.3 ? 'start' : dx < -0.3 ? 'end' : 'middle';
    return /*#__PURE__*/React.createElement("text", {
      key: 'sl' + i,
      x: lx,
      y: ly,
      fontFamily: MONO,
      fontSize: "9.5",
      fill: "#3A3830",
      letterSpacing: "0.02em",
      textAnchor: anchor
    }, sphereNames[i]);
  }), [4, 3, 2, 1, 0].map(i => {
    const cy = lcyBase - i * ldy;
    const pts = [[lcx, cy - lvh], [lcx + lhw, cy], [lcx, cy + lvh], [lcx - lhw, cy]];
    return /*#__PURE__*/React.createElement("g", {
      key: 'ly' + i
    }, /*#__PURE__*/React.createElement("polygon", {
      points: pts.map(p => p.join(',')).join(' '),
      fill: layerTint[i],
      opacity: "0.92",
      stroke: "#6BA37C",
      strokeWidth: "1"
    }), /*#__PURE__*/React.createElement("text", {
      x: lcx,
      y: cy + 9,
      fontFamily: MONO,
      fontSize: "10.5",
      fontWeight: "500",
      letterSpacing: "0.03em",
      textAnchor: "middle",
      fill: "#0E2419",
      stroke: "#FBFAF3",
      strokeWidth: "3.4",
      strokeLinejoin: "round",
      paintOrder: "stroke"
    }, layerNames[i]));
  }), modeRows.map((cy, i) => /*#__PURE__*/React.createElement("g", {
    key: 'md' + i
  }, /*#__PURE__*/React.createElement("line", {
    x1: mcx - mdx + 15,
    y1: cy,
    x2: mcx + mdx - 15,
    y2: cy,
    stroke: "#C9C6BD",
    strokeWidth: "1.4"
  }), glyph(modeKinds[i][0], mcx - mdx, cy), glyph(modeKinds[i][1], mcx + mdx, cy), /*#__PURE__*/React.createElement("text", {
    x: mcx,
    y: cy + 34,
    fontFamily: MONO,
    fontSize: "9.5",
    fill: "#807D72",
    letterSpacing: "0.12em",
    textAnchor: "middle"
  }, modeLabels[i])))));
};

/* ---------- Modes diagram (standalone hero version — human/agent icon pairs) ---------- */
const ModesDiagram = ({
  onSelect
}) => {
  const MONO = 'JetBrains Mono, monospace';
  const SERIF = 'Instrument Serif, serif';
  const humanColor = '#1F4D2E',
    agentColor = '#3F8657';
  const human = (cx, cy) => /*#__PURE__*/React.createElement("g", {
    fill: humanColor
  }, /*#__PURE__*/React.createElement("circle", {
    cx: cx,
    cy: cy - 22,
    r: 17
  }), /*#__PURE__*/React.createElement("path", {
    d: `M ${cx - 30} ${cy + 28} a 30 30 0 0 1 60 0 Z`
  }));
  const agent = (cx, cy) => /*#__PURE__*/React.createElement("g", {
    fill: agentColor
  }, /*#__PURE__*/React.createElement("line", {
    x1: cx,
    y1: cy - 26,
    x2: cx,
    y2: cy - 40,
    stroke: agentColor,
    strokeWidth: 5
  }), /*#__PURE__*/React.createElement("circle", {
    cx: cx,
    cy: cy - 42,
    r: 6
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx - 10,
    y: cy - 12,
    width: 7,
    height: 20,
    rx: 3.5
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx + 3,
    y: cy - 12,
    width: 7,
    height: 20,
    rx: 3.5
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx - 28,
    y: cy - 28,
    width: 56,
    height: 50,
    rx: 12
  }), /*#__PURE__*/React.createElement("circle", {
    cx: cx - 12,
    cy: cy - 5,
    r: 6,
    fill: "#fff"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: cx + 12,
    cy: cy - 5,
    r: 6,
    fill: "#fff"
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx - 14,
    y: cy + 11,
    width: 28,
    height: 6,
    rx: 3,
    fill: "#fff"
  }));
  const rows = [{
    key: 'h2h',
    left: 'h',
    right: 'h',
    label: 'HUMAN ↔ HUMAN',
    lineColor: '#2A6B3C'
  }, {
    key: 'h2a',
    left: 'h',
    right: 'a',
    label: 'HUMAN ↔ AGENT',
    lineColor: '#5C5A50'
  }, {
    key: 'a2a',
    left: 'a',
    right: 'a',
    label: 'AGENT ↔ AGENT',
    lineColor: '#3A3830'
  }];
  const lx = 130,
    rx = 470,
    rowH = 140,
    startY = 240;
  return /*#__PURE__*/React.createElement("div", {
    className: "diagram-axes",
    style: {
      maxWidth: 700,
      margin: '48px auto'
    }
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 600 660",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Three modes of collaboration"
  }, /*#__PURE__*/React.createElement("text", {
    x: 300,
    y: 90,
    fontFamily: SERIF,
    fontSize: "68",
    fill: "#0E2419",
    textAnchor: "middle"
  }, "3"), /*#__PURE__*/React.createElement("text", {
    x: 300,
    y: 128,
    fontFamily: MONO,
    fontSize: "12",
    fill: "#807D72",
    letterSpacing: "0.24em",
    textAnchor: "middle"
  }, "MODES"), rows.map((r, i) => {
    const cy = startY + i * rowH;
    return /*#__PURE__*/React.createElement("g", {
      key: i,
      className: onSelect ? 'diagram-node' : undefined,
      onClick: onSelect ? () => onSelect(r.key) : undefined,
      tabIndex: onSelect ? 0 : undefined,
      role: onSelect ? 'button' : undefined,
      "aria-label": onSelect ? `Jump to ${r.label}` : undefined,
      onKeyDown: onSelect ? e => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(r.key);
        }
      } : undefined
    }, /*#__PURE__*/React.createElement("line", {
      x1: lx + 42,
      y1: cy,
      x2: rx - 42,
      y2: cy,
      stroke: r.lineColor,
      strokeWidth: "1.6",
      strokeDasharray: "6 5"
    }), r.left === 'h' ? human(lx, cy) : agent(lx, cy), r.right === 'h' ? human(rx, cy) : agent(rx, cy), /*#__PURE__*/React.createElement("text", {
      x: 300,
      y: cy + 66,
      fontFamily: MONO,
      fontSize: "12",
      fill: "#5C5A50",
      letterSpacing: "0.22em",
      textAnchor: "middle"
    }, r.label));
  })));
};

/* ---------- Three small column diagrams for Why page ---------- */
const SpheresColDiagram = () => {
  const MONO = 'JetBrains Mono, monospace';
  const sphereNames = ['Value', 'Work', 'Relationship', 'Learning', 'Communication'];
  const sphereTints = ['#1F4D2E', '#2D6B41', '#3F8657', '#6BA37C', '#9CBFA3'];
  const cx = 140,
    cy = 120,
    R = 70,
    r = 22;
  const pts = sphereTints.map((_, i) => {
    const a = -Math.PI / 2 + i * 2 * Math.PI / 5;
    return [cx + R * Math.cos(a), cy + R * Math.sin(a), a];
  });
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 280 210",
    preserveAspectRatio: "xMidYMid meet",
    style: {
      width: '100%',
      display: 'block'
    }
  }, /*#__PURE__*/React.createElement("polygon", {
    points: pts.map(p => `${p[0]},${p[1]}`).join(' '),
    fill: "none",
    stroke: "#9CBFA3",
    strokeWidth: "1",
    opacity: "0.4"
  }), pts.map((p, i) => /*#__PURE__*/React.createElement("circle", {
    key: i,
    cx: p[0],
    cy: p[1],
    r: r,
    fill: sphereTints[i],
    opacity: "0.9"
  })), pts.map((p, i) => {
    const dx = Math.cos(p[2]),
      dy = Math.sin(p[2]);
    const lx = cx + (R + r + 8) * dx,
      ly = cy + (R + r + 8) * dy + 3;
    const anchor = dx > 0.3 ? 'start' : dx < -0.3 ? 'end' : 'middle';
    return /*#__PURE__*/React.createElement("text", {
      key: i,
      x: lx,
      y: ly,
      fontFamily: MONO,
      fontSize: "9",
      fill: "#3A3830",
      textAnchor: anchor,
      letterSpacing: "0.02em"
    }, sphereNames[i]);
  }));
};
const LayersColDiagram = () => {
  const MONO = 'JetBrains Mono, monospace';
  const cx = 140,
    cyBase = 195,
    hw = 90,
    hh = 22,
    step = 38;
  const layerNames = ['Individual', 'Team', 'Organization', 'Family', 'Ecosystem'];
  const layerTints = ['#9CBFA3', '#AECFB5', '#C0D9C4', '#D4E7D7', '#E8F2E9'];
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 280 215",
    preserveAspectRatio: "xMidYMid meet",
    style: {
      width: '100%',
      display: 'block'
    }
  }, [4, 3, 2, 1, 0].map(i => {
    const cy = cyBase - i * step;
    const pts = `${cx},${cy - hh} ${cx + hw},${cy} ${cx},${cy + hh} ${cx - hw},${cy}`;
    return /*#__PURE__*/React.createElement("g", {
      key: i
    }, /*#__PURE__*/React.createElement("polygon", {
      points: pts,
      fill: layerTints[i],
      stroke: "#6BA37C",
      strokeWidth: "1"
    }), /*#__PURE__*/React.createElement("text", {
      x: cx,
      y: cy + 4,
      fontFamily: MONO,
      fontSize: "10",
      fontWeight: "500",
      textAnchor: "middle",
      fill: "#0E2419",
      stroke: "#FBFAF3",
      strokeWidth: "3",
      strokeLinejoin: "round",
      paintOrder: "stroke"
    }, layerNames[i]));
  }));
};
const ModesColDiagram = () => {
  const MONO = 'JetBrains Mono, monospace';
  const s = 1.25;
  const humanColor = '#1F4D2E',
    agentColor = '#3F8657';
  const human = (cx, cy) => /*#__PURE__*/React.createElement("g", {
    fill: humanColor
  }, /*#__PURE__*/React.createElement("circle", {
    cx: cx,
    cy: cy - 8 * s,
    r: 6 * s
  }), /*#__PURE__*/React.createElement("path", {
    d: `M ${cx - 12 * s} ${cy + 12 * s} a ${12 * s} ${12 * s} 0 0 1 ${24 * s} 0 Z`
  }));
  const agent = (cx, cy) => /*#__PURE__*/React.createElement("g", {
    fill: agentColor
  }, /*#__PURE__*/React.createElement("line", {
    x1: cx,
    y1: cy - 10 * s,
    x2: cx,
    y2: cy - 17 * s,
    stroke: agentColor,
    strokeWidth: 1.8 * s
  }), /*#__PURE__*/React.createElement("circle", {
    cx: cx,
    cy: cy - 18 * s,
    r: 2.5 * s
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx - 14 * s,
    y: cy - 4 * s,
    width: 3 * s,
    height: 8 * s,
    rx: 1.5 * s
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx + 11 * s,
    y: cy - 4 * s,
    width: 3 * s,
    height: 8 * s,
    rx: 1.5 * s
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx - 11 * s,
    y: cy - 10 * s,
    width: 22 * s,
    height: 20 * s,
    rx: 5 * s
  }), /*#__PURE__*/React.createElement("circle", {
    cx: cx - 5 * s,
    cy: cy - 2 * s,
    r: 2.5 * s,
    fill: "#fff"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: cx + 5 * s,
    cy: cy - 2 * s,
    r: 2.5 * s,
    fill: "#fff"
  }), /*#__PURE__*/React.createElement("rect", {
    x: cx - 5.5 * s,
    y: cy + 4 * s,
    width: 11 * s,
    height: 2.2 * s,
    rx: 1.1 * s,
    fill: "#fff"
  }));
  const rows = [{
    left: 'h',
    right: 'h',
    label: 'HUMAN ↔ HUMAN',
    lc: '#2A6B3C'
  }, {
    left: 'h',
    right: 'a',
    label: 'HUMAN ↔ AGENT',
    lc: '#5C5A50'
  }, {
    left: 'a',
    right: 'a',
    label: 'AGENT ↔ AGENT',
    lc: '#3A3830'
  }];
  const lx = 44,
    rx = 236,
    rowH = 66,
    startY = 40;
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 280 255",
    preserveAspectRatio: "xMidYMid meet",
    style: {
      width: '100%',
      display: 'block'
    }
  }, rows.map((r, i) => {
    const cy = startY + i * rowH;
    return /*#__PURE__*/React.createElement("g", {
      key: i
    }, /*#__PURE__*/React.createElement("line", {
      x1: lx + 20,
      y1: cy,
      x2: rx - 20,
      y2: cy,
      stroke: r.lc,
      strokeWidth: "1.2",
      strokeDasharray: "4 3"
    }), r.left === 'h' ? human(lx, cy) : agent(lx, cy), r.right === 'h' ? human(rx, cy) : agent(rx, cy), /*#__PURE__*/React.createElement("text", {
      x: 140,
      y: cy + 32,
      fontFamily: MONO,
      fontSize: "9",
      fill: "#807D72",
      letterSpacing: "0.18em",
      textAnchor: "middle"
    }, r.label));
  }));
};

/* ---------- Layers stack (standalone hero version of the layers column) ---------- */
const LayersDiagram = ({
  onSelect
}) => {
  const MONO = 'JetBrains Mono, monospace';
  const SERIF = 'Instrument Serif, serif';
  const cx = 360,
    cyBase = 540,
    hw = 200,
    hh = 44,
    step = 78;
  const layerNames = ['Individual', 'Team', 'Organization', 'Family', 'Ecosystem'];
  const layerKeys = ['individual', 'team', 'org', 'family', 'ecosystem'];
  const layerNumerals = ['I', 'II', 'III', 'IV', 'V'];
  const layerTints = ['#9CBFA3', '#AECFB5', '#C0D9C4', '#D4E7D7', '#E8F2E9'];
  return /*#__PURE__*/React.createElement("div", {
    className: "diagram-axes",
    style: {
      maxWidth: 700,
      margin: '48px auto'
    }
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 720 660",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Five layers of organizational scale"
  }, /*#__PURE__*/React.createElement("text", {
    x: cx,
    y: 90,
    fontFamily: SERIF,
    fontSize: "68",
    fill: "#0E2419",
    textAnchor: "middle"
  }, "5"), /*#__PURE__*/React.createElement("text", {
    x: cx,
    y: 128,
    fontFamily: MONO,
    fontSize: "12",
    fill: "#807D72",
    letterSpacing: "0.24em",
    textAnchor: "middle"
  }, "LAYERS"), [4, 3, 2, 1, 0].map(i => {
    const cy = cyBase - i * step;
    const pts = `${cx},${cy - hh} ${cx + hw},${cy} ${cx},${cy + hh} ${cx - hw},${cy}`;
    return /*#__PURE__*/React.createElement("g", {
      key: i,
      className: onSelect ? 'diagram-node' : undefined,
      onClick: onSelect ? () => onSelect(layerKeys[i]) : undefined,
      tabIndex: onSelect ? 0 : undefined,
      role: onSelect ? 'button' : undefined,
      "aria-label": onSelect ? `Jump to the ${layerNames[i]} layer` : undefined,
      onKeyDown: onSelect ? e => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(layerKeys[i]);
        }
      } : undefined
    }, /*#__PURE__*/React.createElement("polygon", {
      points: pts,
      fill: layerTints[i],
      stroke: "#6BA37C",
      strokeWidth: "1.4"
    }), /*#__PURE__*/React.createElement("text", {
      x: cx - hw - 24,
      y: cy + 5,
      fontFamily: MONO,
      fontSize: "11",
      fill: "#6BA37C",
      letterSpacing: "0.18em",
      textAnchor: "end"
    }, layerNumerals[i]), /*#__PURE__*/React.createElement("text", {
      x: cx,
      y: cy + 6,
      fontFamily: MONO,
      fontSize: "14",
      fontWeight: "500",
      letterSpacing: "0.06em",
      textAnchor: "middle",
      fill: "#0E2419",
      stroke: "#FBFAF3",
      strokeWidth: "4",
      strokeLinejoin: "round",
      paintOrder: "stroke"
    }, layerNames[i]));
  })));
};

/* ---------- Nested circles (5 layers, individual at core) ---------- */
const NestedCircles = ({
  activeLayer = null
}) => {
  const LAYERS = [{
    key: 'ecosystem',
    label: 'Ecosystem',
    r: 320,
    dy: 0
  }, {
    key: 'family',
    label: 'Organization Family',
    r: 256,
    dy: 0
  }, {
    key: 'org',
    label: 'Organization',
    r: 192,
    dy: 0
  }, {
    key: 'team',
    label: 'Team',
    r: 128,
    dy: 0
  }, {
    key: 'individual',
    label: 'Individual',
    r: 64,
    dy: 0
  }];
  return /*#__PURE__*/React.createElement("div", {
    className: "nested-circles"
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "-360 -360 720 720",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Five nested layers, individual at the core"
  }, /*#__PURE__*/React.createElement("defs", null, /*#__PURE__*/React.createElement("radialGradient", {
    id: "coreFill",
    cx: "50%",
    cy: "50%",
    r: "50%"
  }, /*#__PURE__*/React.createElement("stop", {
    offset: "0%",
    stopColor: "#1F4D2E"
  }), /*#__PURE__*/React.createElement("stop", {
    offset: "100%",
    stopColor: "#163322"
  }))), LAYERS.map((l, i) => {
    const isActive = activeLayer === l.key;
    const isCore = l.key === 'individual';
    const stroke = isCore ? 'none' : '#9CBFA3';
    const fill = isCore ? 'url(#coreFill)' : '#FFFFFF';
    return /*#__PURE__*/React.createElement("g", {
      key: l.key
    }, /*#__PURE__*/React.createElement("circle", {
      cx: "0",
      cy: "0",
      r: l.r,
      fill: fill,
      stroke: stroke,
      strokeWidth: isActive ? 2 : 1,
      strokeOpacity: isActive ? 1 : 0.6,
      strokeDasharray: i === 0 ? '6 4' : 'none'
    }), /*#__PURE__*/React.createElement("text", {
      x: "0",
      y: isCore ? 4 : -l.r + (i === 0 ? -14 : 18),
      textAnchor: "middle",
      fontFamily: isCore ? 'Instrument Serif, serif' : 'JetBrains Mono, monospace',
      fontSize: isCore ? 16 : 11,
      fontWeight: isCore ? 400 : 500,
      fill: isCore ? '#FFFFFF' : '#3A3830',
      letterSpacing: isCore ? '-0.02em' : '0.22em'
    }, isCore ? l.label : l.label.toUpperCase()));
  }), /*#__PURE__*/React.createElement("g", {
    stroke: "#9CBFA3",
    strokeWidth: "0.6",
    opacity: "0.45",
    fill: "none"
  }, [0, 1, 2, 3, 4, 5].map(i => {
    const a = i / 6 * Math.PI * 2;
    const x1 = Math.cos(a) * 64,
      y1 = Math.sin(a) * 64;
    const x2 = Math.cos(a + 0.6) * 192,
      y2 = Math.sin(a + 0.6) * 192;
    const x3 = Math.cos(a + 1.1) * 320,
      y3 = Math.sin(a + 1.1) * 320;
    return /*#__PURE__*/React.createElement("path", {
      key: i,
      d: `M ${x1} ${y1} Q ${(x1 + x2) / 2 + 12} ${(y1 + y2) / 2 - 12} ${x2} ${y2} T ${x3} ${y3}`
    });
  })), /*#__PURE__*/React.createElement("g", {
    fill: "#1F4D2E"
  }, [[128, 0.4], [192, 1.3], [192, 4.6], [256, 2.0], [256, 5.1], [320, 0.9], [320, 3.3], [320, 5.7]].map(([r, a], i) => /*#__PURE__*/React.createElement("circle", {
    key: i,
    cx: Math.cos(a) * r,
    cy: Math.sin(a) * r,
    r: "3.2"
  })))));
};

/* ---------- Modes triad ---------- */
const ModesTriad = () => /*#__PURE__*/React.createElement("div", {
  className: "triad"
}, /*#__PURE__*/React.createElement("svg", {
  viewBox: "0 0 680 390",
  preserveAspectRatio: "xMidYMid meet",
  role: "img",
  "aria-label": "Three modes: human-to-human, human-to-agent, agent-to-agent"
}, /*#__PURE__*/React.createElement("defs", null, /*#__PURE__*/React.createElement("radialGradient", {
  id: "mt-h",
  cx: "38%",
  cy: "32%",
  r: "70%"
}, /*#__PURE__*/React.createElement("stop", {
  offset: "0%",
  stopColor: "#4A9E63"
}), /*#__PURE__*/React.createElement("stop", {
  offset: "100%",
  stopColor: "#1F4D2E"
})), /*#__PURE__*/React.createElement("radialGradient", {
  id: "mt-a",
  cx: "38%",
  cy: "32%",
  r: "70%"
}, /*#__PURE__*/React.createElement("stop", {
  offset: "0%",
  stopColor: "#6B6960"
}), /*#__PURE__*/React.createElement("stop", {
  offset: "100%",
  stopColor: "#14130E"
})), /*#__PURE__*/React.createElement("marker", {
  id: "arr-hh-e",
  viewBox: "0 0 8 8",
  refX: "7",
  refY: "4",
  markerWidth: "5",
  markerHeight: "5",
  orient: "auto"
}, /*#__PURE__*/React.createElement("path", {
  d: "M1 1 L7 4 L1 7",
  fill: "none",
  stroke: "#2A6B3C",
  strokeWidth: "1.5",
  strokeLinejoin: "round"
})), /*#__PURE__*/React.createElement("marker", {
  id: "arr-hh-s",
  viewBox: "0 0 8 8",
  refX: "1",
  refY: "4",
  markerWidth: "5",
  markerHeight: "5",
  orient: "auto-start-reverse"
}, /*#__PURE__*/React.createElement("path", {
  d: "M1 1 L7 4 L1 7",
  fill: "none",
  stroke: "#2A6B3C",
  strokeWidth: "1.5",
  strokeLinejoin: "round"
})), /*#__PURE__*/React.createElement("marker", {
  id: "arr-ha-e",
  viewBox: "0 0 8 8",
  refX: "7",
  refY: "4",
  markerWidth: "5",
  markerHeight: "5",
  orient: "auto"
}, /*#__PURE__*/React.createElement("path", {
  d: "M1 1 L7 4 L1 7",
  fill: "none",
  stroke: "#5C5A50",
  strokeWidth: "1.5",
  strokeLinejoin: "round"
})), /*#__PURE__*/React.createElement("marker", {
  id: "arr-ha-s",
  viewBox: "0 0 8 8",
  refX: "1",
  refY: "4",
  markerWidth: "5",
  markerHeight: "5",
  orient: "auto-start-reverse"
}, /*#__PURE__*/React.createElement("path", {
  d: "M1 1 L7 4 L1 7",
  fill: "none",
  stroke: "#5C5A50",
  strokeWidth: "1.5",
  strokeLinejoin: "round"
})), /*#__PURE__*/React.createElement("marker", {
  id: "arr-aa-e",
  viewBox: "0 0 8 8",
  refX: "7",
  refY: "4",
  markerWidth: "5",
  markerHeight: "5",
  orient: "auto"
}, /*#__PURE__*/React.createElement("path", {
  d: "M1 1 L7 4 L1 7",
  fill: "none",
  stroke: "#3A3830",
  strokeWidth: "1.5",
  strokeLinejoin: "round"
})), /*#__PURE__*/React.createElement("marker", {
  id: "arr-aa-s",
  viewBox: "0 0 8 8",
  refX: "1",
  refY: "4",
  markerWidth: "5",
  markerHeight: "5",
  orient: "auto-start-reverse"
}, /*#__PURE__*/React.createElement("path", {
  d: "M1 1 L7 4 L1 7",
  fill: "none",
  stroke: "#3A3830",
  strokeWidth: "1.5",
  strokeLinejoin: "round"
}))), /*#__PURE__*/React.createElement("g", null, /*#__PURE__*/React.createElement("text", {
  x: "28",
  y: "81",
  fontFamily: "JetBrains Mono, monospace",
  fontSize: "10",
  fill: "#2A6B3C",
  letterSpacing: "0.2em",
  fontWeight: "600"
}, "I"), /*#__PURE__*/React.createElement("line", {
  x1: "178",
  y1: "76",
  x2: "502",
  y2: "76",
  stroke: "#2A6B3C",
  strokeWidth: "1.4",
  markerEnd: "url(#arr-hh-e)",
  markerStart: "url(#arr-hh-s)"
}), /*#__PURE__*/React.createElement("rect", {
  x: "278",
  y: "62",
  width: "124",
  height: "26",
  rx: "4",
  fill: "#FBFAF3"
}), /*#__PURE__*/React.createElement("text", {
  x: "340",
  y: "79",
  textAnchor: "middle",
  fontFamily: "JetBrains Mono, monospace",
  fontSize: "10",
  fill: "#2A6B3C",
  letterSpacing: "0.2em"
}, "H \u2194 H"), /*#__PURE__*/React.createElement("circle", {
  cx: "138",
  cy: "76",
  r: "38",
  fill: "url(#mt-h)"
}), /*#__PURE__*/React.createElement("text", {
  x: "138",
  y: "71",
  textAnchor: "middle",
  fontFamily: "Instrument Serif, serif",
  fontSize: "16",
  fill: "#fff"
}, "Human"), /*#__PURE__*/React.createElement("text", {
  x: "138",
  y: "87",
  textAnchor: "middle",
  fontFamily: "Hanken Grotesk, sans-serif",
  fontSize: "9",
  fill: "#A8CDB0",
  letterSpacing: "0.07em"
}, "practitioner"), /*#__PURE__*/React.createElement("circle", {
  cx: "542",
  cy: "76",
  r: "38",
  fill: "url(#mt-h)"
}), /*#__PURE__*/React.createElement("text", {
  x: "542",
  y: "71",
  textAnchor: "middle",
  fontFamily: "Instrument Serif, serif",
  fontSize: "16",
  fill: "#fff"
}, "Human"), /*#__PURE__*/React.createElement("text", {
  x: "542",
  y: "87",
  textAnchor: "middle",
  fontFamily: "Hanken Grotesk, sans-serif",
  fontSize: "9",
  fill: "#A8CDB0",
  letterSpacing: "0.07em"
}, "practitioner")), /*#__PURE__*/React.createElement("g", null, /*#__PURE__*/React.createElement("text", {
  x: "28",
  y: "201",
  fontFamily: "JetBrains Mono, monospace",
  fontSize: "10",
  fill: "#5C5A50",
  letterSpacing: "0.2em",
  fontWeight: "600"
}, "II"), /*#__PURE__*/React.createElement("line", {
  x1: "178",
  y1: "196",
  x2: "502",
  y2: "196",
  stroke: "#5C5A50",
  strokeWidth: "1.4",
  markerEnd: "url(#arr-ha-e)",
  markerStart: "url(#arr-ha-s)"
}), /*#__PURE__*/React.createElement("rect", {
  x: "278",
  y: "182",
  width: "124",
  height: "26",
  rx: "4",
  fill: "#FBFAF3"
}), /*#__PURE__*/React.createElement("text", {
  x: "340",
  y: "199",
  textAnchor: "middle",
  fontFamily: "JetBrains Mono, monospace",
  fontSize: "10",
  fill: "#5C5A50",
  letterSpacing: "0.2em"
}, "H \u2194 A"), /*#__PURE__*/React.createElement("circle", {
  cx: "138",
  cy: "196",
  r: "38",
  fill: "url(#mt-h)"
}), /*#__PURE__*/React.createElement("text", {
  x: "138",
  y: "191",
  textAnchor: "middle",
  fontFamily: "Instrument Serif, serif",
  fontSize: "16",
  fill: "#fff"
}, "Human"), /*#__PURE__*/React.createElement("text", {
  x: "138",
  y: "207",
  textAnchor: "middle",
  fontFamily: "Hanken Grotesk, sans-serif",
  fontSize: "9",
  fill: "#A8CDB0",
  letterSpacing: "0.07em"
}, "practitioner"), /*#__PURE__*/React.createElement("circle", {
  cx: "542",
  cy: "196",
  r: "38",
  fill: "url(#mt-a)"
}), /*#__PURE__*/React.createElement("text", {
  x: "542",
  y: "191",
  textAnchor: "middle",
  fontFamily: "Instrument Serif, serif",
  fontSize: "16",
  fill: "#fff"
}, "Agent"), /*#__PURE__*/React.createElement("text", {
  x: "542",
  y: "207",
  textAnchor: "middle",
  fontFamily: "Hanken Grotesk, sans-serif",
  fontSize: "9",
  fill: "#B0AEA4",
  letterSpacing: "0.07em"
}, "assistant")), /*#__PURE__*/React.createElement("g", null, /*#__PURE__*/React.createElement("text", {
  x: "28",
  y: "321",
  fontFamily: "JetBrains Mono, monospace",
  fontSize: "10",
  fill: "#3A3830",
  letterSpacing: "0.2em",
  fontWeight: "600"
}, "III"), /*#__PURE__*/React.createElement("line", {
  x1: "178",
  y1: "316",
  x2: "502",
  y2: "316",
  stroke: "#3A3830",
  strokeWidth: "1.4",
  markerEnd: "url(#arr-aa-e)",
  markerStart: "url(#arr-aa-s)"
}), /*#__PURE__*/React.createElement("rect", {
  x: "278",
  y: "302",
  width: "124",
  height: "26",
  rx: "4",
  fill: "#FBFAF3"
}), /*#__PURE__*/React.createElement("text", {
  x: "340",
  y: "319",
  textAnchor: "middle",
  fontFamily: "JetBrains Mono, monospace",
  fontSize: "10",
  fill: "#3A3830",
  letterSpacing: "0.2em"
}, "A \u2194 A"), /*#__PURE__*/React.createElement("circle", {
  cx: "138",
  cy: "316",
  r: "38",
  fill: "url(#mt-a)"
}), /*#__PURE__*/React.createElement("text", {
  x: "138",
  y: "311",
  textAnchor: "middle",
  fontFamily: "Instrument Serif, serif",
  fontSize: "16",
  fill: "#fff"
}, "Agent"), /*#__PURE__*/React.createElement("text", {
  x: "138",
  y: "327",
  textAnchor: "middle",
  fontFamily: "Hanken Grotesk, sans-serif",
  fontSize: "9",
  fill: "#B0AEA4",
  letterSpacing: "0.07em"
}, "worker"), /*#__PURE__*/React.createElement("circle", {
  cx: "542",
  cy: "316",
  r: "38",
  fill: "url(#mt-a)"
}), /*#__PURE__*/React.createElement("text", {
  x: "542",
  y: "311",
  textAnchor: "middle",
  fontFamily: "Instrument Serif, serif",
  fontSize: "16",
  fill: "#fff"
}, "Agent"), /*#__PURE__*/React.createElement("text", {
  x: "542",
  y: "327",
  textAnchor: "middle",
  fontFamily: "Hanken Grotesk, sans-serif",
  fontSize: "9",
  fill: "#B0AEA4",
  letterSpacing: "0.07em"
}, "worker")), /*#__PURE__*/React.createElement("line", {
  x1: "60",
  y1: "136",
  x2: "620",
  y2: "136",
  stroke: "#D6D0C4",
  strokeWidth: "0.8",
  strokeDasharray: "4 6"
}), /*#__PURE__*/React.createElement("line", {
  x1: "60",
  y1: "256",
  x2: "620",
  y2: "256",
  stroke: "#D6D0C4",
  strokeWidth: "0.8",
  strokeDasharray: "4 6"
})));

/* ---------- Spheres orbit (5 spheres around the brand mark) ---------- */
const SpheresOrbit = ({
  onSelect
}) => {
  const SPHERES = [{
    key: 'value',
    label: 'Value'
  }, {
    key: 'work',
    label: 'Work'
  }, {
    key: 'rel',
    label: 'Relationship'
  }, {
    key: 'learn',
    label: 'Learning'
  }, {
    key: 'comm',
    label: 'Communication'
  }];
  const radius = 230;
  return /*#__PURE__*/React.createElement("div", {
    className: "spheres-orbit"
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "-340 -340 680 680",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Five spheres of organizational life"
  }, /*#__PURE__*/React.createElement("defs", null, /*#__PURE__*/React.createElement("radialGradient", {
    id: "orbitGlow",
    cx: "50%",
    cy: "50%",
    r: "50%"
  }, /*#__PURE__*/React.createElement("stop", {
    offset: "0%",
    stopColor: "#E2EBDD",
    stopOpacity: "0.7"
  }), /*#__PURE__*/React.createElement("stop", {
    offset: "100%",
    stopColor: "#E2EBDD",
    stopOpacity: "0"
  }))), /*#__PURE__*/React.createElement("circle", {
    cx: "0",
    cy: "0",
    r: "320",
    fill: "url(#orbitGlow)"
  }), /*#__PURE__*/React.createElement("g", {
    stroke: "#9CBFA3",
    strokeWidth: "1",
    fill: "none",
    opacity: "0.7"
  }, /*#__PURE__*/React.createElement("circle", {
    cx: "0",
    cy: "0",
    r: radius,
    strokeDasharray: "3 5"
  })), /*#__PURE__*/React.createElement("g", {
    stroke: "#6BA37C",
    strokeWidth: "0.7",
    fill: "none",
    opacity: "0.45"
  }, SPHERES.map((s, i) => SPHERES.slice(i + 1).map((t, j) => {
    const aA = i / SPHERES.length * Math.PI * 2 - Math.PI / 2;
    const k = SPHERES.indexOf(t);
    const aB = k / SPHERES.length * Math.PI * 2 - Math.PI / 2;
    const x1 = Math.cos(aA) * radius,
      y1 = Math.sin(aA) * radius;
    const x2 = Math.cos(aB) * radius,
      y2 = Math.sin(aB) * radius;
    return /*#__PURE__*/React.createElement("path", {
      key: `${i}-${j}`,
      d: `M ${x1} ${y1} Q 0 0 ${x2} ${y2}`
    });
  }))), /*#__PURE__*/React.createElement("g", null, /*#__PURE__*/React.createElement("circle", {
    cx: "0",
    cy: "0",
    r: "68",
    fill: "#FFFFFF",
    stroke: "#1F4D2E",
    strokeWidth: "1.5"
  }), /*#__PURE__*/React.createElement("image", {
    href: "assets/audax-os-logo-512.png",
    x: "-48",
    y: "-48",
    width: "96",
    height: "96",
    preserveAspectRatio: "xMidYMid meet"
  }), /*#__PURE__*/React.createElement("text", {
    x: "0",
    y: "110",
    textAnchor: "middle",
    fontFamily: "JetBrains Mono, monospace",
    fontSize: "10",
    letterSpacing: "0.22em",
    fill: "#1F4D2E",
    fontWeight: "500"
  }, "AUDAX OS")), SPHERES.map((s, i) => {
    const a = i / SPHERES.length * Math.PI * 2 - Math.PI / 2;
    const x = Math.cos(a) * radius;
    const y = Math.sin(a) * radius;
    return /*#__PURE__*/React.createElement("g", {
      key: s.key,
      transform: `translate(${x} ${y})`,
      className: onSelect ? 'diagram-node' : undefined,
      onClick: onSelect ? () => onSelect(s.key) : undefined,
      tabIndex: onSelect ? 0 : undefined,
      role: onSelect ? 'button' : undefined,
      "aria-label": onSelect ? `Jump to the ${s.label} sphere` : undefined,
      onKeyDown: onSelect ? e => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(s.key);
        }
      } : undefined
    }, /*#__PURE__*/React.createElement("circle", {
      cx: "0",
      cy: "0",
      r: "54",
      fill: "#FFFFFF",
      stroke: "#1F4D2E",
      strokeWidth: "1.5"
    }), /*#__PURE__*/React.createElement("circle", {
      cx: "0",
      cy: "0",
      r: "40",
      fill: "none",
      stroke: "#9CBFA3",
      strokeWidth: "0.7"
    }), /*#__PURE__*/React.createElement("text", {
      x: "0",
      y: "3",
      textAnchor: "middle",
      fontFamily: "Instrument Serif, serif",
      fontSize: "16",
      fontWeight: "400",
      fill: "#14130E",
      letterSpacing: "-0.015em"
    }, s.label.split(' ')[0]), /*#__PURE__*/React.createElement("text", {
      x: "0",
      y: "76",
      textAnchor: "middle",
      fontFamily: "JetBrains Mono, monospace",
      fontSize: "9",
      fill: "#807D72",
      letterSpacing: "0.18em"
    }, `SPHERE ${['I', 'II', 'III', 'IV', 'V'][i]}`));
  })));
};

/* ---------- Causal Loop (single regenerative ring) ---------- */
const CausalLoop = () => {
  const NODES = [{
    label: 'Value',
    glyph: 'I'
  }, {
    label: 'Trust',
    glyph: 'III'
  }, {
    label: 'Communication',
    glyph: 'V'
  }, {
    label: 'Work',
    glyph: 'II'
  }, {
    label: 'Learning',
    glyph: 'IV'
  }];
  const radius = 200;
  return /*#__PURE__*/React.createElement("div", {
    className: "causal-loop"
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "-280 -260 560 520",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Causal loop between the five spheres"
  }, /*#__PURE__*/React.createElement("g", {
    fill: "none",
    stroke: "#1F4D2E",
    strokeWidth: "1.6",
    strokeLinecap: "round"
  }, NODES.map((n, i) => {
    const a1 = i / NODES.length * Math.PI * 2 - Math.PI / 2;
    const a2 = (i + 1) / NODES.length * Math.PI * 2 - Math.PI / 2;
    const x1 = Math.cos(a1) * radius,
      y1 = Math.sin(a1) * radius;
    const x2 = Math.cos(a2) * radius,
      y2 = Math.sin(a2) * radius;
    const dx = x2 - x1,
      dy = y2 - y1;
    const len = Math.hypot(dx, dy);
    const ex = x2 - dx / len * 60,
      ey = y2 - dy / len * 60;
    const sx = x1 + dx / len * 60,
      sy = y1 + dy / len * 60;
    const mx = (sx + ex) / 2 - dy * 0.18;
    const my = (sy + ey) / 2 + dx * 0.18;
    const ang = Math.atan2(ey - my, ex - mx) * 180 / Math.PI;
    return /*#__PURE__*/React.createElement("g", {
      key: i
    }, /*#__PURE__*/React.createElement("path", {
      d: `M ${sx} ${sy} Q ${mx} ${my} ${ex} ${ey}`
    }), /*#__PURE__*/React.createElement("polygon", {
      points: "0,-5 10,0 0,5",
      transform: `translate(${ex} ${ey}) rotate(${ang})`,
      fill: "#1F4D2E"
    }));
  })), NODES.map((n, i) => {
    const a = i / NODES.length * Math.PI * 2 - Math.PI / 2;
    const x = Math.cos(a) * radius;
    const y = Math.sin(a) * radius;
    return /*#__PURE__*/React.createElement("g", {
      key: n.label,
      transform: `translate(${x} ${y})`
    }, /*#__PURE__*/React.createElement("circle", {
      cx: "0",
      cy: "0",
      r: "48",
      fill: "#FFFFFF",
      stroke: "#1F4D2E",
      strokeWidth: "1.5"
    }), /*#__PURE__*/React.createElement("text", {
      x: "0",
      y: "-2",
      textAnchor: "middle",
      fontFamily: "Instrument Serif, serif",
      fontSize: "16",
      fontWeight: "400",
      fill: "#14130E",
      letterSpacing: "-0.015em"
    }, n.label), /*#__PURE__*/React.createElement("text", {
      x: "0",
      y: "15",
      textAnchor: "middle",
      fontFamily: "JetBrains Mono, monospace",
      fontSize: "9",
      fill: "#807D72",
      letterSpacing: "0.18em"
    }, n.glyph));
  })));
};

/* ---------- Two loops (degenerative vs regenerative) ---------- */
const TwoLoops = () => {
  const ITEMS_DEG = ['Invisible contribution', 'Weaker trust', 'Guarded communication', 'Confused work', 'Defensive learning', 'Distorted value'];
  const ITEMS_REG = ['Visible contribution', 'Stronger trust', 'Clearer communication', 'Better work', 'Deeper learning', 'Fairer value'];
  const Loop = ({
    title,
    items,
    kind
  }) => /*#__PURE__*/React.createElement("div", {
    className: `loop loop-${kind}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "loop-title"
  }, title), /*#__PURE__*/React.createElement("ol", {
    className: "loop-list"
  }, items.map((it, i) => /*#__PURE__*/React.createElement("li", {
    key: it
  }, /*#__PURE__*/React.createElement("span", {
    className: "i"
  }, String(i + 1).padStart(2, '0')), /*#__PURE__*/React.createElement("span", {
    className: "t"
  }, it))), /*#__PURE__*/React.createElement("li", {
    className: "close"
  }, /*#__PURE__*/React.createElement("span", {
    className: "i"
  }, "\u21BB"), /*#__PURE__*/React.createElement("span", {
    className: "t"
  }, "back to ", items[0].toLowerCase()))));
  return /*#__PURE__*/React.createElement("div", {
    className: "two-loops"
  }, /*#__PURE__*/React.createElement(Loop, {
    title: "Degenerative loop",
    items: ITEMS_DEG,
    kind: "ink"
  }), /*#__PURE__*/React.createElement(Loop, {
    title: "Regenerative loop",
    items: ITEMS_REG,
    kind: "forest"
  }));
};

/* ---------- Health wheel (5-part diagnostic) ---------- */
const HealthWheel = ({
  scores
}) => {
  const SPHERES = ['Value', 'Work', 'Relationship', 'Learning', 'Communication'];
  const s = scores || [0.85, 0.65, 0.55, 0.35, 0.75];
  const R = 200;
  return /*#__PURE__*/React.createElement("div", {
    className: "health-wheel"
  }, /*#__PURE__*/React.createElement("svg", {
    viewBox: "-280 -260 560 520",
    preserveAspectRatio: "xMidYMid meet",
    role: "img",
    "aria-label": "Five-sphere diagnostic wheel"
  }, /*#__PURE__*/React.createElement("g", {
    fill: "none",
    stroke: "#E3E0D6",
    strokeWidth: "1"
  }, [0.25, 0.5, 0.75, 1].map(t => /*#__PURE__*/React.createElement("circle", {
    key: t,
    cx: "0",
    cy: "0",
    r: R * t
  }))), /*#__PURE__*/React.createElement("g", {
    stroke: "#E3E0D6",
    strokeWidth: "1"
  }, SPHERES.map((_, i) => {
    const a = i / SPHERES.length * Math.PI * 2 - Math.PI / 2;
    return /*#__PURE__*/React.createElement("line", {
      key: i,
      x1: "0",
      y1: "0",
      x2: Math.cos(a) * R,
      y2: Math.sin(a) * R
    });
  })), /*#__PURE__*/React.createElement("polygon", {
    points: SPHERES.map((_, i) => {
      const a = i / SPHERES.length * Math.PI * 2 - Math.PI / 2;
      return `${Math.cos(a) * R * s[i]},${Math.sin(a) * R * s[i]}`;
    }).join(' '),
    fill: "#1F4D2E",
    fillOpacity: "0.18",
    stroke: "#1F4D2E",
    strokeWidth: "1.5"
  }), SPHERES.map((_, i) => {
    const a = i / SPHERES.length * Math.PI * 2 - Math.PI / 2;
    return /*#__PURE__*/React.createElement("circle", {
      key: i,
      cx: Math.cos(a) * R * s[i],
      cy: Math.sin(a) * R * s[i],
      r: "5",
      fill: s[i] < 0.5 ? '#B8C766' : '#1F4D2E'
    });
  }), SPHERES.map((name, i) => {
    const a = i / SPHERES.length * Math.PI * 2 - Math.PI / 2;
    const x = Math.cos(a) * (R + 32);
    const y = Math.sin(a) * (R + 32);
    return /*#__PURE__*/React.createElement("text", {
      key: name,
      x: x,
      y: y + 5,
      textAnchor: "middle",
      fontFamily: "Instrument Serif, serif",
      fontSize: "18",
      fontWeight: "400",
      fill: "#14130E",
      letterSpacing: "-0.015em"
    }, name);
  })));
};
Object.assign(window, {
  MatrixDiagram,
  NestedCircles,
  ModesTriad,
  SpheresOrbit,
  CausalLoop,
  TwoLoops,
  HealthWheel
});