/* Generated from li-extras.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/* Living Intelligence · extras
   The triad diagram, the step list and the copyable prompt. Kept apart from the
   page so the page file stays readable. */

/* ─── The triad, drawn ───────────────────────────────────────────────────
   Three overlapping circles in the manner of the Human x AI x biosphere figure that
   Alexander drew for the camp, redrawn in this site's palette with the Biosphere first.
   Lichen for the Biosphere, a warm clay for Human, sage mist for AI. Each circle lists the
   five orienting qualities from that figure; each pairwise overlap names what the two
   share; the center carries the aim. Hovering or focusing a set lifts its circle.

   Geometry: three circles of radius 250 whose centers form an equilateral triangle
   of side ~271, so the pairwise lenses and the triple center all have room for text. */
const TRI_R = 250;
const TRI_C = {
  n: [500, 290],
  h: [362, 528],
  a: [638, 528]
};
const TRI_SETS = {
  n: {
    name: 'Biosphere',
    color: '#C7D27B',
    text: '#EEF0D2',
    at: [500, 94],
    gap: 31,
    step: 29.5,
    items: ['Regeneration', 'Resilience', 'Health of ecosystems', 'Interdependence', 'More-than-human life']
  },
  h: {
    name: 'Human',
    color: '#E9A673',
    text: '#FBE6D3',
    at: [272, 508],
    gap: 38,
    step: 31,
    items: ['Dignity', 'Agency', 'Flourishing', 'Equity', 'Meaning']
  },
  a: {
    name: 'AI',
    color: '#C8DBC9',
    text: '#E2EBDD',
    at: [728, 508],
    gap: 38,
    step: 31,
    items: ['Augmentation', 'Alignment', 'Governance', 'Transparency', 'Responsibility']
  }
};
const TRI_PAIRS = [{
  id: 'nh',
  at: [352, 350],
  lines: ['Kinship', 'Stewardship'],
  color: '#DDE0A0'
}, {
  id: 'na',
  at: [648, 350],
  lines: ['Known origins', 'Tangible impact'],
  color: '#D6E4C6'
}, {
  id: 'ha',
  at: [500, 626],
  lines: ['Consent', 'Answerability'],
  color: '#EBCDB0'
}];
const TRI_ZOOMS = [1, 1.6, 2.3, 3.2];
const TriadDiagram = () => {
  const ref = useCampReveal();
  const [hot, setHot] = React.useState(null);
  const [zi, setZi] = React.useState(0);
  const scroller = React.useRef(null);
  const zoom = TRI_ZOOMS[zi];

  // keep the middle of the figure in view as it grows or shrinks
  React.useEffect(() => {
    const el = scroller.current;
    if (!el) return;
    el.scrollLeft = (el.scrollWidth - el.clientWidth) / 2;
    el.scrollTop = 0;
  }, [zi]);
  const keys = ['n', 'h', 'a'];
  const lift = k => ({
    onMouseEnter: () => setHot(k),
    onMouseLeave: () => setHot(null),
    onFocus: () => setHot(k),
    onBlur: () => setHot(null)
  });
  return /*#__PURE__*/React.createElement("div", {
    className: "li-tri-wrap"
  }, /*#__PURE__*/React.createElement("div", {
    className: "li-tri-scroll",
    ref: scroller
  }, /*#__PURE__*/React.createElement("svg", {
    ref: ref,
    className: "li-tri",
    "data-hot": hot || undefined,
    style: zoom > 1 ? {
      width: `${zoom * 100}%`
    } : undefined,
    viewBox: "96 24 808 776",
    role: "img",
    "aria-label": "Three overlapping circles for the Biosphere, Human and AI. Where all three meet: coevolution for a regenerative future."
  }, keys.map((k, i) => {
    const s = TRI_SETS[k];
    const [cx, cy] = TRI_C[k];
    return /*#__PURE__*/React.createElement("g", {
      key: k,
      className: `li-tri-c${hot === k ? ' hot' : ''}${hot && hot !== k ? ' dim' : ''}`
    }, /*#__PURE__*/React.createElement("circle", {
      className: "fill",
      cx: cx,
      cy: cy,
      r: TRI_R,
      fill: s.color
    }), /*#__PURE__*/React.createElement("circle", {
      className: "ring",
      cx: cx,
      cy: cy,
      r: TRI_R,
      fill: "none",
      stroke: s.color,
      pathLength: "1",
      style: {
        transitionDelay: `${i * 180}ms`
      }
    }));
  }), keys.map((k, i) => {
    const s = TRI_SETS[k];
    const [x, y] = s.at;
    return /*#__PURE__*/React.createElement("g", {
      key: k,
      className: "lbl",
      style: {
        transitionDelay: `${500 + i * 120}ms`
      }
    }, /*#__PURE__*/React.createElement("g", _extends({
      className: "li-tri-set",
      tabIndex: 0,
      "aria-label": `${s.name}: ${s.items.join(', ')}`
    }, lift(k)), /*#__PURE__*/React.createElement("text", {
      className: "t-title",
      x: x,
      y: y,
      textAnchor: "middle",
      fill: s.color
    }, s.name), s.items.map((it, j) => /*#__PURE__*/React.createElement("text", {
      key: it,
      className: "t-item",
      x: x,
      y: y + s.gap + j * s.step,
      textAnchor: "middle",
      fill: s.text
    }, it))));
  }), TRI_PAIRS.map((p, i) => /*#__PURE__*/React.createElement("g", {
    key: p.id,
    className: "lbl",
    style: {
      transitionDelay: `${900 + i * 100}ms`
    }
  }, p.lines.map((ln, j) => /*#__PURE__*/React.createElement("text", {
    key: ln,
    className: "t-pair",
    x: p.at[0],
    y: p.at[1] + j * 21,
    textAnchor: "middle",
    fill: p.color
  }, ln)))), /*#__PURE__*/React.createElement("g", {
    className: "lbl",
    style: {
      transitionDelay: '1200ms'
    }
  }, /*#__PURE__*/React.createElement("path", {
    className: "li-tri-seed",
    d: "M500 394 C507 402 507 411 500 419 C493 411 493 402 500 394 Z"
  }), /*#__PURE__*/React.createElement("text", {
    className: "t-core",
    x: "500",
    y: "452",
    textAnchor: "middle"
  }, "Coevolution"), /*#__PURE__*/React.createElement("text", {
    className: "t-core2",
    x: "500",
    y: "478",
    textAnchor: "middle"
  }, "for a regenerative"), /*#__PURE__*/React.createElement("text", {
    className: "t-core2",
    x: "500",
    y: "499",
    textAnchor: "middle"
  }, "future")))), /*#__PURE__*/React.createElement("div", {
    className: "li-tri-zoom",
    role: "group",
    "aria-label": "Zoom the diagram"
  }, /*#__PURE__*/React.createElement("button", {
    type: "button",
    "aria-label": "Zoom out",
    disabled: zi === 0,
    onClick: () => setZi(z => Math.max(0, z - 1))
  }, "\u2212"), /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "fit",
    "aria-label": "Fit to screen",
    disabled: zi === 0,
    onClick: () => setZi(0)
  }, "Fit"), /*#__PURE__*/React.createElement("button", {
    type: "button",
    "aria-label": "Zoom in",
    disabled: zi === TRI_ZOOMS.length - 1,
    onClick: () => setZi(z => Math.min(TRI_ZOOMS.length - 1, z + 1))
  }, "+")), /*#__PURE__*/React.createElement("p", {
    className: "li-tri-hint"
  }, "Pinch or use the buttons to zoom, then drag to look around."), /*#__PURE__*/React.createElement("div", {
    className: "li-tri-list"
  }, keys.map(k => /*#__PURE__*/React.createElement("div", {
    key: k,
    className: "li-tri-card",
    style: {
      '--tri': TRI_SETS[k].color
    }
  }, /*#__PURE__*/React.createElement("h4", null, TRI_SETS[k].name), /*#__PURE__*/React.createElement("p", null, TRI_SETS[k].items.join(' · ')))), /*#__PURE__*/React.createElement("div", {
    className: "li-tri-card li-tri-card-core"
  }, /*#__PURE__*/React.createElement("h4", null, "Where they meet"), /*#__PURE__*/React.createElement("p", null, "Kinship \xB7 Stewardship \xB7 Known origins \xB7 Tangible impact \xB7 Consent \xB7 Answerability"), /*#__PURE__*/React.createElement("p", {
    className: "core"
  }, "Coevolution for a regenerative future"))));
};

/* ─── From property to build ─────────────────────────────────────────────
   Seven steps that alternate between an AI drafting and people deciding. */
const LISteps = ({
  steps
}) => /*#__PURE__*/React.createElement(CampCascade, {
  as: "ol",
  step: 80,
  className: "li-steps"
}, steps.map((s, i) => /*#__PURE__*/React.createElement("li", {
  key: s.title,
  className: `li-step ${s.who === 'People decide' || s.who === 'People' ? 'people' : 'ai'}`
}, /*#__PURE__*/React.createElement("span", {
  className: "n"
}, String(i + 1).padStart(2, '0')), /*#__PURE__*/React.createElement("div", {
  className: "b"
}, /*#__PURE__*/React.createElement("h4", null, s.title), /*#__PURE__*/React.createElement("p", null, s.body)), /*#__PURE__*/React.createElement("span", {
  className: "who"
}, s.who))));

/* ─── A prompt to take away ──────────────────────────────────────────────
   Paste it into any assistant, add a few sentences about your own work, and get a
   first map of how that work meets the properties. */
const LI_PROMPT = `You are a thoughtful collaborator helping me find the questions that matter most about the relationship between the Biosphere, human beings and AI. These questions are where Living Intelligence begins: a shared north star that turns questions into Desirable Properties, conditions specific enough to build toward and to disagree about. Three sets orient the work:
- Biosphere: regeneration, resilience, health of ecosystems, interdependence, more-than-human life
- Human: dignity, agency, flourishing, equity, meaning
- AI: augmentation, alignment, governance, transparency, responsibility
Where the three meet, the aim is coevolution for a regenerative future.

Use what you already know about my work from this project or space: its files, notes, past conversations and any instructions I have given you. Where something is unclear or missing, ask me before assuming.

Please respond with questions:
1. Five questions my work raises about how the Biosphere, people and AI can flourish together, drawn from both my concerns and my aspirations.
2. For each question, the property it points toward, from the lists above or a new one.
3. One question I may be avoiding and why it matters.
4. One question I could take to the people I work with this week and a small experiment that would explore it (observe, orient, decide, act).
5. Two kinds of people or organizations to ask these questions, with the first thing to ask each.
6. One question the lists above leave out.

Finish by asking me which question I would most like others to explore, and help me sharpen it into one sentence I can share with the Living Intelligence community.`;
const LIPrompt = () => {
  const [copied, setCopied] = React.useState(false);
  const copy = () => {
    const done = () => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2400);
    };
    if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(LI_PROMPT).then(done, done);else done();
  };
  return /*#__PURE__*/React.createElement("div", {
    className: "li-prompt"
  }, /*#__PURE__*/React.createElement("div", {
    className: "li-prompt-head"
  }, /*#__PURE__*/React.createElement("span", null, "Copy into your AI project or space"), /*#__PURE__*/React.createElement("button", {
    type: "button",
    onClick: copy,
    "aria-live": "polite"
  }, copied ? 'Copied' : 'Copy prompt')), /*#__PURE__*/React.createElement("pre", null, LI_PROMPT));
};

/* ─── Links and calls ────────────────────────────────────────────────────
   LI_TELEGRAM_URL: the group's invite link. Empty means the Telegram buttons and
   lines stay hidden; paste the link here and they appear everywhere at once.

   LI_LUMA_EVENTS: the next Camp Audax call on The Coherence Company's calendar
   (luma.com/thecoherenceco), by Luma event slug: Wed 30 Sep 2026 and Wed 7 Oct 2026.
   Swap in the newest two whenever new calls are scheduled. */
const LI_TELEGRAM_URL = 'https://t.me/+msbQmsbxpAg4Yjk8'; // the Audax OS group; the older Camp Audax page used this invite
const LI_LUMA_EVENTS = ['4h2zh57m'];

/* Luma's embed cannot be restyled and only lays out compactly from 700px wide, so
   the iframe stays 700x460 and .cph-luma-card scales it down for small screens. */
const LILumaCarousel = ({
  ids
}) => /*#__PURE__*/React.createElement("div", {
  style: {
    display: 'flex',
    gap: 16,
    overflowX: 'auto',
    paddingBottom: 8,
    scrollSnapType: 'x mandatory',
    WebkitOverflowScrolling: 'touch'
  }
}, ids.map(id => /*#__PURE__*/React.createElement("div", {
  key: id,
  className: "cph-luma-card"
}, /*#__PURE__*/React.createElement("iframe", {
  src: `https://lu.ma/embed/event/${id}/simple`,
  width: "700",
  height: "460",
  allow: "fullscreen; payment",
  title: "Camp Audax call, hosted on Luma",
  loading: "lazy"
}))));

/* An empty picture frame: holds the place of a photograph until we have our own. */
const LIPlate = ({
  index,
  caption,
  ratio = '21 / 9'
}) => /*#__PURE__*/React.createElement("figure", {
  className: "li-plate-solo"
}, /*#__PURE__*/React.createElement("div", {
  className: "li-plate-frame",
  style: {
    aspectRatio: ratio
  },
  role: "img",
  "aria-label": "Image to come"
}, /*#__PURE__*/React.createElement("span", null, "Image to come")), caption && /*#__PURE__*/React.createElement("figcaption", {
  className: "cph-aside-cap"
}, index && /*#__PURE__*/React.createElement("span", {
  className: "cph-plate-idx"
}, index), caption));
Object.assign(window, {
  LIPlate,
  TriadDiagram,
  LISteps,
  LIPrompt,
  LI_PROMPT,
  LI_TELEGRAM_URL,
  LI_LUMA_EVENTS,
  LILumaCarousel
});