/* Generated from li-kit.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
function _extends() { return _extends = Object.assign ? Object.assign.bind() : function (n) { for (var e = 1; e < arguments.length; e++) { var t = arguments[e]; for (var r in t) ({}).hasOwnProperty.call(t, r) && (n[r] = t[r]); } return n; }, _extends.apply(null, arguments); }
/* Living Intelligence · component kit
   The Camp Audax page devices (page-camp.jsx) that Living Intelligence adjusts, kept as LI-prefixed
   copies so the camp page stays exactly as it is. Every other Camp* / cph* helper is shared
   with page-camp.jsx and used as is. */

/* A section title: the plain clause rises, the italic accent bleeds in
   out of focus and sharpens. Used on all six q-h1s and the closing h2,
   and deliberately never on the hero, which keeps the typewriter. */
const LICampInk = ({
  as: Tag = 'h1',
  className = '',
  children,
  ...rest
}) => {
  const ref = useCampReveal(el => {
    cphWrapWords(el, 'cph-ink-plain', cphInkPick);
    // read through the title: plain words follow one another, the accent settles after them
    let plain = 0,
      accent = 0;
    el.querySelectorAll('.cph-ink-plain, .cph-ink-em').forEach(w => {
      w.style.transitionDelay = w.classList.contains('cph-ink-em') ? `${260 + Math.min(accent++, 14) * 55}ms` : `${Math.min(plain++, 14) * 38}ms`;
    });
  });
  return /*#__PURE__*/React.createElement(Tag, _extends({
    ref: ref,
    className: `cph-ink${className ? ' ' + className : ''}`
  }, rest), children);
};
const LICampBand = ({
  shot,
  kicker,
  label,
  rate = 0.16,
  tear,
  tearTop,
  tearGround,
  tearGroundTop,
  cta,
  featured
}) => {
  const band = React.useRef(null);
  const art = React.useRef(null);
  React.useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    let ticking = false;
    const frame = () => {
      ticking = false;
      const el = band.current,
        a = art.current;
      if (!el || !a) return;
      const r = el.getBoundingClientRect();
      const vh = window.innerHeight;
      if (r.bottom < -200 || r.top > vh + 200) return;
      // -1 below the fold → 1 above it
      const p = (r.top + r.height / 2 - vh / 2) / (vh / 2 + r.height / 2);
      a.style.transform = `translate3d(0,${(p * rate * r.height).toFixed(1)}px,0)`;
    };
    const onScroll = () => {
      if (!ticking) {
        ticking = true;
        requestAnimationFrame(frame);
      }
    };
    window.addEventListener('scroll', onScroll, {
      passive: true
    });
    window.addEventListener('resize', onScroll);
    frame();
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
    };
  }, [rate]);
  return /*#__PURE__*/React.createElement("div", {
    className: `cph-band${featured ? ' li-band-feature' : ''}`,
    ref: band
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-band-art",
    ref: art,
    style: {
      backgroundImage: `url(${CPH(shot)})`
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "cph-veil cph-band-veil"
  }), tearTop && /*#__PURE__*/React.createElement(CampTear, {
    image: tearTop,
    edge: "top",
    ground: tearGroundTop,
    flip: true
  }), tear && /*#__PURE__*/React.createElement(CampTear, {
    image: tear,
    edge: "bottom",
    ground: tearGround
  }), /*#__PURE__*/React.createElement("div", {
    className: "cph-band-inner"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-band-kicker"
  }, kicker), /*#__PURE__*/React.createElement("div", {
    className: "cph-band-label"
  }, label), cta && /*#__PURE__*/React.createElement("a", {
    className: "btn btn-join btn-lg li-band-cta",
    href: cta.href,
    target: "_blank",
    rel: "noreferrer"
  }, /*#__PURE__*/React.createElement("span", null, cta.label), /*#__PURE__*/React.createElement("i", {
    "data-lucide": "arrow-right"
  }))));
};

/* ─── Pattern 04 · sticky diptych ────────────────────────────────────────
   One image pinned while the movements scroll past it. */
const LICampDiptych = ({
  items,
  label = 'Example',
  compact
}) => {
  const [active, setActive] = React.useState(0);
  const steps = React.useRef([]);
  React.useEffect(() => {
    const els = steps.current.filter(Boolean);
    if (!els.length || !('IntersectionObserver' in window)) return;
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (e.isIntersecting) setActive(els.indexOf(e.target));
      });
    }, {
      rootMargin: '-45% 0px -45% 0px',
      threshold: 0
    });
    els.forEach(el => io.observe(el));
    return () => io.disconnect();
  }, [items]);

  /* Continuous focus on top of the discrete `active` above. The observer
     picks which photograph shows — a step change, correctly. The type
     wants the opposite: --near falls off smoothly with each step's
     distance from the read line, so titles grow and recede as the reader
     scrolls rather than snapping between two opacities. The .on class
     stays as the reduced-motion and no-JS fallback, which is why
     .cph-focus is only added when this driver is actually running. */
  const col = React.useRef(null);
  React.useEffect(() => {
    const els = steps.current.filter(Boolean);
    if (!els.length || cphReduced()) return undefined;
    if (col.current) col.current.classList.add('cph-focus');
    return cphAddTick(() => {
      const vh = window.innerHeight || 1;
      const line = vh * 0.5;
      els.forEach(el => {
        const r = el.getBoundingClientRect();
        const d = Math.abs(r.top + r.height / 2 - line) / (vh * 0.45);
        el.style.setProperty('--near', cphClamp(1 - d).toFixed(3));
      });
    });
  }, [items]);
  return /*#__PURE__*/React.createElement("div", {
    className: "cph-dip-grid"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-dip-media"
  }, items.map((m, n) => /*#__PURE__*/React.createElement("div", {
    key: m.n,
    className: `cph-shot${n === active ? ' on' : ''}`,
    style: {
      backgroundImage: `url(${CPH(m.shot)})`
    },
    role: "img",
    "aria-label": `${label} ${m.n} - ${m.title}`
  }))), /*#__PURE__*/React.createElement("div", {
    className: `cph-steps${compact ? ' li-q-steps' : ''}`,
    ref: col
  }, items.map((m, n) => /*#__PURE__*/React.createElement("div", {
    key: m.n,
    ref: el => {
      steps.current[n] = el;
    },
    className: `cph-step${n === active ? ' on' : ''}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "n"
  }, label, " ", m.n), /*#__PURE__*/React.createElement("h4", null, m.title), m.body && /*#__PURE__*/React.createElement("p", null, m.body)))));
};
const LICampSignposts = ({
  active,
  onJump
}) => {
  const [open, setOpen] = React.useState(false);
  const jumpAndClose = id => {
    onJump(id);
    setOpen(false);
  };
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("nav", {
    className: "cph-signposts",
    "aria-label": "Jump to a section"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-sp-posts"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-sp-rope"
  }), LI_SECTIONS.map(s => /*#__PURE__*/React.createElement("button", {
    key: s.id,
    className: `cph-sp-post${active === s.id ? ' active' : ''}`,
    onClick: () => onJump(s.id),
    type: "button",
    "aria-label": `Jump to ${s.label}`,
    "aria-current": active === s.id ? 'true' : undefined
  }, /*#__PURE__*/React.createElement("span", {
    className: "cph-sp-badge"
  }, s.icon), /*#__PURE__*/React.createElement("span", {
    className: "cph-sp-tag"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mile"
  }, s.mile), /*#__PURE__*/React.createElement("span", {
    className: "lab"
  }, s.label)))))), /*#__PURE__*/React.createElement("button", {
    className: `cph-sp-burger${open ? ' open' : ''}`,
    type: "button",
    onClick: () => setOpen(o => !o),
    "aria-label": open ? 'Close section menu' : 'Open section menu',
    "aria-expanded": open
  }, /*#__PURE__*/React.createElement("span", null), /*#__PURE__*/React.createElement("span", null), /*#__PURE__*/React.createElement("span", null)), /*#__PURE__*/React.createElement("div", {
    className: `cph-sp-scrim${open ? ' show' : ''}`,
    onClick: () => setOpen(false)
  }), /*#__PURE__*/React.createElement("aside", {
    className: `cph-sp-drawer${open ? ' open' : ''}`,
    "aria-hidden": !open
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-sp-drawer-head"
  }, /*#__PURE__*/React.createElement("span", {
    className: "kicker"
  }, "Living Intelligence"), /*#__PURE__*/React.createElement("button", {
    className: "cph-sp-drawer-close",
    type: "button",
    onClick: () => setOpen(false),
    "aria-label": "Close menu"
  }, "\u2715")), /*#__PURE__*/React.createElement("div", {
    className: "cph-sp-drawer-list"
  }, LI_SECTIONS.map(s => /*#__PURE__*/React.createElement("button", {
    key: s.id,
    className: `cph-sp-drawer-it${active === s.id ? ' active' : ''}`,
    onClick: () => jumpAndClose(s.id),
    type: "button",
    "aria-current": active === s.id ? 'true' : undefined
  }, /*#__PURE__*/React.createElement("span", {
    className: "icon"
  }, s.icon), /*#__PURE__*/React.createElement("span", {
    className: "meta"
  }, /*#__PURE__*/React.createElement("span", {
    className: "lab"
  }, s.label), /*#__PURE__*/React.createElement("span", {
    className: "mile"
  }, s.mile))))), /*#__PURE__*/React.createElement("div", {
    className: "cph-sp-drawer-foot"
  }, /*#__PURE__*/React.createElement("button", {
    className: "cph-sp-drawer-cta",
    type: "button",
    onClick: () => window.open(LI_JOIN_URL, '_blank')
  }, LI_CTA))));
};
const LICampWhyCome = ({
  items
}) => {
  const [paused, setPaused] = React.useState(false);
  const chip = dup => items.map(([title], i) => /*#__PURE__*/React.createElement("span", {
    className: "cph-why-chip",
    key: (dup ? 'b' : 'a') + title
  }, /*#__PURE__*/React.createElement("span", {
    className: "n"
  }, String(i + 1).padStart(2, '0')), /*#__PURE__*/React.createElement("span", {
    className: "t"
  }, title)));
  // the three that answer "what is this, where is it, what do I leave with"
  const glosses = [0, 2, 5].map(i => items[i]).filter(Boolean);
  return /*#__PURE__*/React.createElement("section", {
    className: "section-tight cph-why-sec"
  }, /*#__PURE__*/React.createElement("div", {
    className: "container cph-why-head"
  }, /*#__PURE__*/React.createElement(CampKicker, {
    bottom: 20
  }, "The big ideas \xB7 ", items.length, " threads to hold"), /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "cph-why-pause",
    onClick: () => setPaused(p => !p),
    "aria-pressed": paused
  }, paused ? 'Play' : 'Pause')), /*#__PURE__*/React.createElement("div", {
    className: `cph-why-ribbon${paused ? ' paused' : ''}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-why-track"
  }, chip(false), /*#__PURE__*/React.createElement("span", {
    "aria-hidden": "true",
    style: {
      display: 'contents'
    }
  }, chip(true)))), /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-why-glosses"
  }, glosses.map(([title, gloss]) => /*#__PURE__*/React.createElement("p", {
    key: title
  }, gloss)))));
};
const LICampPersonaSlider = ({
  profiles
}) => {
  const [active, setActive] = React.useState(0);
  const [autoplay, setAutoplay] = React.useState(true);
  const [fill, setFill] = React.useState(false);
  const AUTOPLAY_MS = 6000;
  React.useEffect(() => {
    if (!autoplay || cphReduced()) return;
    const t = setInterval(() => setActive(a => (a + 1) % profiles.length), AUTOPLAY_MS);
    return () => clearInterval(t);
  }, [autoplay, profiles.length]);
  React.useEffect(() => {
    setFill(false);
    if (!autoplay || cphReduced()) return;
    const raf = requestAnimationFrame(() => setFill(true));
    return () => cancelAnimationFrame(raf);
  }, [active, autoplay]);
  const goTo = i => {
    setActive(i);
    setAutoplay(false);
  };
  const p = profiles[active];
  return /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      marginBottom: 28,
      flexWrap: 'wrap'
    }
  }, /*#__PURE__*/React.createElement("button", {
    type: "button",
    onClick: () => goTo((active - 1 + profiles.length) % profiles.length),
    "aria-label": "Previous",
    style: {
      width: 34,
      height: 34,
      borderRadius: '50%',
      flexShrink: 0,
      border: '1px solid var(--forest-200)',
      background: 'var(--surface-white)',
      color: 'var(--forest-700)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer'
    }
  }, /*#__PURE__*/React.createElement("i", {
    "data-lucide": "chevron-left",
    style: {
      width: 16,
      height: 16
    }
  })), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      gap: 8,
      flexWrap: 'wrap',
      flex: 1
    }
  }, profiles.map((pr, i) => /*#__PURE__*/React.createElement("button", {
    key: pr.n,
    type: "button",
    onClick: () => goTo(i),
    "aria-current": i === active ? 'true' : undefined,
    style: {
      padding: '8px 16px',
      borderRadius: 999,
      cursor: 'pointer',
      fontSize: 13,
      fontWeight: 500,
      fontFamily: 'var(--font-sans)',
      border: i === active ? '1px solid var(--forest-700)' : '1px solid var(--border-1)',
      background: i === active ? 'var(--forest-700)' : 'var(--surface-white)',
      color: i === active ? '#fff' : 'var(--ink-700)',
      position: 'relative',
      overflow: 'hidden'
    }
  }, i === active && /*#__PURE__*/React.createElement("span", {
    key: `${active}-${autoplay}`,
    style: {
      position: 'absolute',
      inset: 0,
      background: 'rgba(255,255,255,0.22)',
      transformOrigin: 'left',
      transform: `scaleX(${fill ? 1 : 0})`,
      transition: fill ? `transform ${AUTOPLAY_MS}ms linear` : 'none'
    },
    "aria-hidden": "true"
  }), /*#__PURE__*/React.createElement("span", {
    style: {
      position: 'relative'
    }
  }, pr.name)))), /*#__PURE__*/React.createElement("button", {
    type: "button",
    onClick: () => goTo((active + 1) % profiles.length),
    "aria-label": "Next",
    style: {
      width: 34,
      height: 34,
      borderRadius: '50%',
      flexShrink: 0,
      border: '1px solid var(--forest-200)',
      background: 'var(--surface-white)',
      color: 'var(--forest-700)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer'
    }
  }, /*#__PURE__*/React.createElement("i", {
    "data-lucide": "chevron-right",
    style: {
      width: 16,
      height: 16
    }
  }))), /*#__PURE__*/React.createElement("div", {
    style: {
      background: 'var(--forest-050)',
      border: '1px solid var(--forest-200)',
      borderRadius: 20,
      padding: 'clamp(28px, 3.5vw, 44px)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)',
      marginBottom: 10
    }
  }, p.n, " of ", profiles.length), /*#__PURE__*/React.createElement("h3", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(24px, 3vw, 32px)',
      fontWeight: 400,
      letterSpacing: '-0.02em',
      color: 'var(--ink-900)',
      margin: '0 0 20px'
    }
  }, p.name), /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(19px, 2.2vw, 25px)',
      fontWeight: 400,
      letterSpacing: '-0.01em',
      lineHeight: 1.35,
      fontStyle: 'italic',
      color: 'var(--forest-900)',
      margin: '0 0 32px',
      maxWidth: 640
    }
  }, p.benefit), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: '1.3fr 1fr',
      gap: 32
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      color: 'var(--ink-500)',
      margin: '0 0 8px'
    }
  }, "What it holds"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-700)',
      margin: 0
    }
  }, p.working)), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      color: 'var(--ink-500)',
      margin: '0 0 8px'
    }
  }, "Candidate properties"), /*#__PURE__*/React.createElement("ul", {
    style: {
      margin: 0,
      padding: 0,
      listStyle: 'none'
    }
  }, p.brings.map(x => /*#__PURE__*/React.createElement("li", {
    key: x,
    style: {
      fontSize: 14,
      fontWeight: 300,
      color: 'var(--ink-800)',
      padding: '3px 0'
    }
  }, x))))), p.blind && /*#__PURE__*/React.createElement("div", {
    style: {
      marginTop: 28,
      paddingTop: 20,
      borderTop: '1px dashed var(--forest-200)'
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      color: 'var(--ink-500)',
      margin: '0 0 8px'
    }
  }, "What it needs the others to show"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--forest-800)',
      margin: 0,
      maxWidth: 640
    }
  }, p.blind))));
};

/* The closing-style band with a photograph that is optional: with no `shot` it stays plain forest green. */
const LICampJoinBand = ({
  shot,
  children,
  note,
  tearTop,
  tearGroundTop,
  tear,
  tearGround,
  pos,
  size
}) => {
  const band = React.useRef(null);
  const art = React.useRef(null);
  React.useEffect(() => {
    if (cphReduced()) return undefined;
    let ticking = false;
    const frame = () => {
      ticking = false;
      const el = band.current,
        a = art.current;
      if (!el || !a) return;
      const r = el.getBoundingClientRect();
      const vh = window.innerHeight;
      if (r.bottom < -200 || r.top > vh + 200) return;
      const p = (r.top + r.height / 2 - vh / 2) / (vh / 2 + r.height / 2);
      a.style.transform = `translate3d(0,${(p * 0.08 * r.height).toFixed(1)}px,0)`;
    };
    const onScroll = () => {
      if (!ticking) {
        ticking = true;
        requestAnimationFrame(frame);
      }
    };
    window.addEventListener('scroll', onScroll, {
      passive: true
    });
    window.addEventListener('resize', onScroll);
    frame();
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
    };
  }, []);
  return /*#__PURE__*/React.createElement("section", {
    className: "cph-join",
    ref: band
  }, shot && /*#__PURE__*/React.createElement("div", {
    className: "cph-join-art",
    ref: art,
    style: {
      backgroundImage: `url(${CPH(shot)})`,
      ...(pos ? {
        backgroundPosition: pos
      } : {}),
      ...(size ? {
        backgroundSize: size
      } : {})
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "cph-join-scrim"
  }), tearTop && /*#__PURE__*/React.createElement(CampTear, {
    image: tearTop,
    edge: "top",
    ground: tearGroundTop,
    flip: true
  }), tear && /*#__PURE__*/React.createElement(CampTear, {
    image: tear,
    edge: "bottom",
    ground: tearGround
  }), /*#__PURE__*/React.createElement("div", {
    className: "container cph-join-inner"
  }, /*#__PURE__*/React.createElement("h2", {
    className: "cph-join-line"
  }, children), /*#__PURE__*/React.createElement(Button, {
    size: "lg",
    variant: "join",
    icon: "arrow-right",
    onClick: () => window.open(LI_JOIN_URL, '_blank')
  }, LI_CTA), note && /*#__PURE__*/React.createElement("p", {
    className: "cph-join-note"
  }, note)));
};
Object.assign(window, {
  LICampJoinBand,
  LICampInk,
  LICampBand,
  LICampDiptych,
  LICampSignposts,
  LICampWhyCome,
  LICampPersonaSlider
});