/* Generated from page-sorrel.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
/* Audax OS site · Sorrel, the camp agent
   ────────────────────────────────────────────────────────────────────────
   This was movement 05 of the camp page. It was the longest section there
   and the only one that asked the reader to care about a piece of software
   before they had decided about a week in a forest, so it moved out to its
   own page. The camp page now points at it from the hero, the closing CTA
   and the FAQ.

   Stand-alone (`chrome: false`), and deliberately built out of the camp
   page's own parts rather than the site's: CampNav, CampFooter, CampInk,
   CampCascade, CampKicker, CampPhoto, CampQuote, SorrelMark and the camp
   note styles are all top-level in page-camp.jsx, which index.html loads
   first. Nothing here is duplicated from it — this file only holds the
   copy that left, and the hero that replaces the section heading. */

/* Not `shadow`: that one runs full-bleed with a caption further down the
   page, and the same photograph twice reads as a mistake rather than a
   motif. */
const SORREL_HERO = 'assets/photos/canopy.webp';

/* What it is, in four claims. Was a 2×2 card grid mid-section; it is the
   summary of the whole page now, so it leads. */
const SORREL_CARDS = [['What it does', 'Explains · orients · synthesizes · connects · remembers · reminds'], ['What it knows', 'Only what you and the rest of us have explicitly allowed it to know.'], ['What it leaves to you', 'What matters to you · who you should work with · what your commitments are worth · every judgment about another human being'], ['How its role changes', 'Before: orientation companion · during: practical navigator and memory keeper · after: reflection partner and bridge to follow-through']];
const SORREL_JOURNEY = [['Before', 'A conversational orientation rather than a form. Why are you coming? What are you building? What questions are alive for you? With your permission, Sorrel introduces relevant themes and surfaces others working on related questions. It shows relevance and explains why. You choose.'], ['During', 'Practical navigation: what is happening now, who is working on what, where a discussion is running, what you have committed to so far. Opt-in Coherence Conversations recording, with everyone present confirming consent and reviewing the synthesis.'], ['After', 'Review what you explored. Remember your commitments. Reconnect with relevant people. Decide what to continue, revise, or release. Collective memory maintained from participant-approved syntheses.']];

/* Sorrel's open questions — the "raise it together" invitation, made
   concrete. Victor: "it's an invitation to together raise the agent."
   Lived in page-camp.jsx as CAMP_UNDECIDED; moved with its section. */
const SORREL_UNDECIDED = [['Its voice', 'Warm or dry. Brief or expansive. Whether it is funny.'], ['Its refusals', 'What it declines to answer, and how it says so.'], ['Its opinions', 'Whether it has any, and whether it volunteers them.'], ['Its presence', 'Whether it speaks at the fire circle or stays out of it.'], ['Its forgetting', 'What it lets go of, when, and who decides.'], ['Its face', 'The mark above is a first sketch, not a decision.']];
const PageSorrel = ({
  onNav
}) => {
  // the camp page's own way of moving between its sections, from a page
  // that is not it: hand the section back through the router
  const jumpToCamp = id => {
    window.location.hash = `#camp/${id}`;
  };
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(CampNav, null), /*#__PURE__*/React.createElement("section", {
    className: "sorrel-hero",
    style: {
      '--sorrel-shot': `url(${SORREL_HERO})`
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "sorrel-hero-shot"
  }), /*#__PURE__*/React.createElement("div", {
    className: "container sorrel-hero-copy"
  }, /*#__PURE__*/React.createElement("a", {
    className: "sorrel-back",
    href: "#camp",
    onClick: e => {
      e.preventDefault();
      onNav ? onNav('camp') : jumpToCamp('why');
    }
  }, "\u2190 Camp Audax"), /*#__PURE__*/React.createElement(SorrelMark, {
    size: 104,
    tone: "var(--lichen-300)"
  }), /*#__PURE__*/React.createElement("h1", {
    className: "display lg"
  }, "Some communities keep a dog. ", /*#__PURE__*/React.createElement("em", null, "We are raising an agent.")), /*#__PURE__*/React.createElement("p", {
    className: "lede"
  }, "Sorrel is the camp\u2019s agent: a working name for something we are building, and would like you to help finish."))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-parchment)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("div", {
    className: "sorrel-intro"
  }, /*#__PURE__*/React.createElement("div", {
    className: "sorrel-nameplate"
  }, /*#__PURE__*/React.createElement(SorrelMark, {
    size: 140
  }), /*#__PURE__*/React.createElement("div", {
    className: "sorrel-name"
  }, "Sorrel"), /*#__PURE__*/React.createElement("div", {
    className: "sorrel-name-note"
  }, "Working name")), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Redwood sorrel carpets the forest floor at Navarro. In direct sun it folds its three leaflets shut; in shade it opens again. We wanted that instinct in an agent, so we borrowed the name."), /*#__PURE__*/React.createElement("p", null, "We have woven Sorrel through the physical experience of our camp. It holds the memory of the week: who is here, what is happening, which conversations are live, which connections have been declared, and what emerged at 7am while you were asleep in a ShiftPod."), /*#__PURE__*/React.createElement("p", null, "It works on consent. It knows only what you choose to tell it. It helps you orient, remember, connect and follow through, and it leaves every judgment that matters to you."), /*#__PURE__*/React.createElement("p", null, "That makes us a live prototype of the thing we are discussing: a consent-based, agent-supported gathering, tested at human scale in a forest."))), /*#__PURE__*/React.createElement(CampCascade, {
    style: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 24,
      marginTop: 48
    }
  }, SORREL_CARDS.map(([h, b]) => /*#__PURE__*/React.createElement("div", {
    key: h,
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 12,
      padding: '20px 22px'
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)',
      margin: '0 0 10px'
    }
  }, h), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 1.55,
      color: 'var(--ink-800)',
      margin: 0
    }
  }, b)))))), /*#__PURE__*/React.createElement(WashRule, {
    image: ART.wave,
    from: "parchment",
    to: "white"
  }), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-white)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(CampInk, {
    as: "h2",
    className: "q-h1"
  }, "A week is three different problems. ", /*#__PURE__*/React.createElement("em", null, "So is the agent.")), /*#__PURE__*/React.createElement(CampKicker, {
    top: 32
  }, "Across the journey"), /*#__PURE__*/React.createElement(CampCascade, {
    className: "contrast-grid",
    style: {
      gridTemplateColumns: '1fr 1fr 1fr'
    }
  }, SORREL_JOURNEY.map(([h, b]) => /*#__PURE__*/React.createElement("div", {
    className: "contrast-col",
    key: h
  }, /*#__PURE__*/React.createElement("h6", null, h), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-800)'
    }
  }, b)))), /*#__PURE__*/React.createElement(CampPhoto, {
    shot: "shadow",
    alt: "Leaf shadows falling across canvas",
    caption: "The same instinct as its name: open in shade, closed in direct light."
  }))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-paper)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(CampInk, {
    as: "h2",
    className: "q-h1"
  }, "Six things about Sorrel ", /*#__PURE__*/React.createElement("em", null, "we have not decided.")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      margin: '24px 0'
    }
  }, /*#__PURE__*/React.createElement("p", null, "Sorrel is not finished, and finishing it is not our job alone \u2014 this is the part we are most directly inviting you into. You and everyone else who comes will set its language, personality, behaviors and boundaries during the week. These are genuinely open:")), /*#__PURE__*/React.createElement(CampCascade, {
    style: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 12,
      marginBottom: 32
    }
  }, SORREL_UNDECIDED.map(([h, b]) => /*#__PURE__*/React.createElement("div", {
    key: h,
    style: {
      padding: '18px 20px',
      background: 'var(--surface-white)',
      border: '1px dashed var(--forest-200)',
      borderRadius: 12
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 17,
      letterSpacing: '-0.01em',
      color: 'var(--ink-900)',
      marginBottom: 6
    }
  }, h), /*#__PURE__*/React.createElement("div", {
    style: {
      fontSize: 13,
      fontWeight: 300,
      lineHeight: 1.5,
      color: 'var(--ink-700)'
    }
  }, b)))), /*#__PURE__*/React.createElement("div", {
    style: {
      ...campNote,
      marginBottom: 24
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: campNoteH6
  }, "And one experiment we are curious about"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 15,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--forest-900)',
      margin: 0
    }
  }, "Several of us will arrive with agents of our own. Where their people consent, we would like to run the first small trials of agents from different organizations talking to each other on their behalf \u2014 introductions, matching needs to offers, carrying a commitment between two teams. This is early, unglamorous and may not work. We will say so either way.")), /*#__PURE__*/React.createElement("div", {
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 12,
      padding: '20px 22px'
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      color: 'var(--ink-500)',
      margin: '0 0 10px'
    }
  }, "Consent, privacy and attention"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      lineHeight: 1.55,
      color: 'var(--ink-700)',
      margin: '0 0 10px'
    }
  }, "We make recording explicitly opt-in and visible. You can join us fully without using Sorrel at all. You can review, edit, export and delete your own material. You choose what stays private, what we as hosts see, what the rest of the camp sees, and what becomes public."), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      lineHeight: 1.55,
      color: 'var(--ink-700)',
      margin: 0
    }
  }, "Sorrel is available when useful and quiet when it is not. Sometimes the best interface is a recorder on a table or a single physical display, rather than an app pecking at everyone\u2019s pockets in a forest.")), /*#__PURE__*/React.createElement(CampQuote, null, "An agent can remind us of the promise. ", /*#__PURE__*/React.createElement("em", null, "The promise is still ours to make.")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      gap: 12,
      flexWrap: 'wrap',
      marginTop: 40
    }
  }, /*#__PURE__*/React.createElement(Button, {
    size: "lg",
    variant: "join",
    icon: "arrow-right",
    onClick: () => window.open(JOIN_URL, '_blank')
  }, "Help raise Sorrel"), /*#__PURE__*/React.createElement(Button, {
    variant: "secondary",
    onClick: () => onNav ? onNav('camp') : jumpToCamp('why')
  }, "Back to Camp Audax")))), /*#__PURE__*/React.createElement(CampFooter, {
    onJump: jumpToCamp,
    onNav: onNav,
    sectionsLabel: "On the camp page"
  }));
};
window.PageSorrel = PageSorrel;