/* Generated from page-living.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
/* Living Intelligence · the page
   One long, anchored landing page in the same design language as the Camp Audax
   page (see li-kit.jsx and page-camp.jsx). Copy is the collective voice of the camp, and draws on
   Daveed Benjamin's two recommendations at prohumannatureai.com, which stay the
   place to read the full North Star method. Photographs come from the Camp Audax library
   and Unsplash. */

const LI_JOIN_URL = 'https://audax.earth/#camp';
const LI_CTA = 'Meet us at Camp Audax';
const LI_SECTIONS = [{
  id: 'relationship',
  label: 'The relationship',
  mile: 'MI 0',
  icon: '◈'
}, {
  id: 'why',
  label: 'Why',
  mile: 'MI 1',
  icon: '◎'
}, {
  id: 'triad',
  label: 'The triad',
  mile: 'MI 2',
  icon: '◐'
}, {
  id: 'questions',
  label: 'The questions',
  mile: 'MI 3',
  icon: '▲'
}, {
  id: 'properties',
  label: 'Desirable Properties',
  mile: 'MI 4',
  icon: '◇'
}, {
  id: 'field',
  label: 'Weaving the field',
  mile: 'MI 5',
  icon: '▣'
}, {
  id: 'join',
  label: 'Join',
  mile: 'MI 6',
  icon: '❖'
}];

/* Every entry completes "People, the Biosphere and AI, ___". The first is the anchor:
   what crawlers, screen readers and reduced-motion readers get. */
const LI_ROTATION = ['learning to coevolve.', 'nurturing wiser intelligence.', 'tending the same roots.', 'building the vision together.', 'in the flow of regeneration.', 'remembering we are one system.'];
const LI_WHY_COME = [['The Biosphere as a participant', 'The Biosphere, Humanity and AI are three forms of intelligences shaping one future together. The people who steward the living world belong in the room where that future is designed.'], ['A north star before the architecture hardens', 'The defaults set this year will be very hard to unpick later. Better to ask now what the whole system should be true of.'], ['Properties that can be tested', 'Values such as dignity and regeneration point to a direction. A Desirable Properties inquiry will turn them into conditions specific enough to build toward, or disagree about.'], ['Written with people who steward real places', 'Seed banks, watersheds, sacred sites, biodiversity networks. The Biosphere properties start from practice that already exists.'], ['Open to any organization, wherever its people are', 'Grown from Camp Audax and built to widen. Anyone can take part from wherever they work.'], ['Coevolution as the frame', 'Coevolution asks what it takes for three very different intelligences to shape each other well, over very long timescales.']];
const LI_TRIAD = [{
  n: '1',
  name: 'Biosphere',
  short: 'Four billion years of research and development, still running.',
  benefit: 'Four billion years of research and development, still running.',
  working: 'Regeneration, resilience and interdependence at every scale: soil, watersheds, seed banks, forests and the practices of the people who tend them.',
  brings: ['Regenerative timescales', 'Standing for other species', 'Polycentric stewardship', 'Visible cost to the biosphere'],
  blind: 'Its own exposure to decisions made in a language it cannot contest: contracts, models and quarterly plans.'
}, {
  n: '2',
  name: 'Human',
  short: 'The ability to ask what a thing is for.',
  benefit: 'The ability to ask what a thing is for.',
  working: 'Meaning, care and judgment and the shared spaces where people deliberate, disagree and decide together.',
  brings: ['Portability that survives a change of provider', 'Agents that stay answerable', 'Shared spaces communities can govern', 'Individual and collective agency'],
  blind: 'The long timescales, quiet costs, and sophisticated patterns and connections that never reach a dashboard, and what a default chosen in a sprint does ten years on.'
}, {
  n: '3',
  name: 'AI',
  short: 'Pattern, speed and synthesis at a scale beyond any single team.',
  benefit: 'Pattern, speed and synthesis at a scale beyond any single team.',
  working: 'The capacity to sense, model and coordinate across more information than any person or institution can track alone.',
  brings: ['Bounded authority', 'Revocable delegation', 'Compartmentalization', 'Independent monitoring', 'Reliable provenance', 'Multiple centers of control'],
  blind: 'What the data leaves out: whatever was never measured and whoever was never asked.'
}];
const LI_VALUE_PROPERTY = [['Agency', 'Can a person change AI provider without losing years of memory, relationships and context?'], ['Accountability', 'Can anyone see who an agent represents, what authority it holds and how to challenge what it does?'], ['Biosphere flourishing', 'Are the energy, water, materials and land a system uses visible, or invisible because the interaction happens on a screen?'], ['Resilience', 'When one part fails, does the failure stay there, or can one compromised agent or security breach reach a whole environment?']];
const LI_HYPHEN = [['Pro-Human AI', 'Service, loyalty, accountability and control: what AI owes the people it works for.'], ['Pro Human-AI', 'The relationship itself: symbiosis, mutual augmentation and durable boundaries between distinct participants.'], ['Pro Human-Biosphere-AI', 'The living systems both depend on. Cost to the biosphere becomes visible and the health of the whole living system joins the design brief.']];
const LI_STEPS = [{
  title: 'Name the properties',
  who: 'People decide',
  body: 'Desirable Properties emerge from conversation with the people who steward real places, build real tools and fund real work.'
}, {
  title: 'Draft the requirements',
  who: 'AI drafts',
  body: 'Each property becomes a proposed requirement structure: what a system must do, should do and could do.'
}, {
  title: 'Decide together',
  who: 'People decide',
  body: 'A human process edits the wording, raises or lowers the bar and settles which requirements to pursue.'
}, {
  title: 'Propose architectures',
  who: 'AI drafts',
  body: 'Candidate designs are generated for each requirement and compared on their consequences, including who controls them and how people leave.'
}, {
  title: 'Choose collectively',
  who: 'People decide',
  body: 'The group selects the architectures it will build and records the reasons.'
}, {
  title: 'Scaffold the substrate',
  who: 'AI drafts',
  body: 'The chosen architecture becomes code: the smallest foundation that lets anyone create communities and applications that live above the web page.'
}, {
  title: 'Overlay and evolve',
  who: 'People',
  body: 'Communities and applications grow on the shared substrate. Each grants the same basic rights to everyone, enforced by code where possible and patches keep the list alive.'
}];
const LI_STOOL = [['Tools that work', 'Agents, protocols and infrastructure that people can inspect, leave and govern. The properties in this list turn into requirements here.', 'Technology & Architecture'], ['Mindsets that mature', 'Cultural maturity, sometimes called planetary adulthood: the capacity to hold long timescales, other species and other people’s needs in one decision. This maturity belongs to the collective: it grows as shared understanding and collective wisdom across whole communities, and learning systems built for free thinking carry this work.', 'Culture and learning'], ['Equity that reaches everyone', 'A future that is fair, free and flourishing for all, with shelter, food and energy within reach of every household and agency in the hands of the many.', 'Economy and justice']];
const LI_FOREST_LAYERS = [['Shared roots', 'Identity, consent, provenance and memory, agreed once and drawn on by every tool.', 'Everyone holds'], ['Tended in coherence', 'Some capabilities gain from concentrated focus. Whoever does one best tends it and offers it to the rest.', 'One team tends'], ['Each brings something new', 'The novel work each team pursues, kept distinct so the network keeps its variety.', 'Distinct gifts']];
const LI_QUESTIONS = ['How can AI bring the living world into planning, governance and everyday decisions?', 'What would it take for a river’s sensor network to belong to the community that lives along it?', 'Which properties stay valuable if AI capability grows faster than our institutions?', 'Where do individual agency, collective agency and the flourishing of the biosphere reinforce one another?', 'As AI grows more capable, what kind of partnership keeps the biosphere, people and AI all flourishing together?', 'How do our own agents relate to us, to one another and to the living world?', 'Who speaks for the places, species and future generations that cannot attend?', 'What does an inspiring story about all three sound like and who tells it?'];

/* One photograph per question, chosen for the feeling of the question. */
const LI_QUESTION_SHOTS = ['meadow', 'meadow', 'hummingbird', 'hummingbird', 'reading', 'reading', 'forest-circle', 'forest-circle'];
const LI_QUESTION_ITEMS = LI_QUESTIONS.map((q, i) => ({
  n: String(i + 1),
  shot: LI_QUESTION_SHOTS[i],
  title: q
}));

/* ─── The mark ───────────────────────────────────────────────────────────
   Three circles, one overlap: biosphere, human, AI, and the lens where they meet. */
const LIMark = ({
  size = 34
}) => /*#__PURE__*/React.createElement("svg", {
  width: size,
  height: size,
  viewBox: "0 0 40 40",
  role: "img",
  "aria-label": "Living Intelligence",
  className: "li-mark"
}, /*#__PURE__*/React.createElement("circle", {
  cx: "20",
  cy: "13",
  r: "9.5",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: "1.4"
}), /*#__PURE__*/React.createElement("circle", {
  cx: "13.5",
  cy: "24.5",
  r: "9.5",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: "1.4"
}), /*#__PURE__*/React.createElement("circle", {
  cx: "26.5",
  cy: "24.5",
  r: "9.5",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: "1.4"
}), /*#__PURE__*/React.createElement("path", {
  d: "M20 18.2 C22.6 20.4 22.6 23.6 20 25.8 C17.4 23.6 17.4 20.4 20 18.2 Z",
  fill: "var(--lichen-400)",
  stroke: "none"
}));

/* ─── Mycelium ───────────────────────────────────────────────────────────
   A seeded, branching network drawn in one stroke per hypha, which draws itself
   as it scrolls into view. Deterministic per seed, so it never changes between
   renders. Used as the relief between sections in place of a plain rule. */
const liRng = seed => {
  let s = seed >>> 0;
  return () => {
    s = s * 1664525 + 1013904223 >>> 0;
    return s / 4294967296;
  };
};

/* A bodhi leaf (Ficus religiosa), base at the origin and tip pointing up: heart-shaped, with the long drip tip. The
   light-ground bands grow bodhi vines, the same leaf as the Living Intelligence graphics. */
const LI_BODHI = 'M0 0 C-2 1 -6.2 -1 -6.2 -5.6 C-6.2 -9.2 -2.8 -11 -1.1 -15.6 C-0.7 -16.8 0.7 -16.8 1.1 -15.6 C2.8 -11 6.2 -9.2 6.2 -5.6 C6.2 -1 2 1 0 0 Z';
const Mycelium = ({
  seed = 7,
  height = 150,
  dark = false
}) => {
  const ref = useCampReveal();
  const {
    paths,
    nodes,
    leaves
  } = React.useMemo(() => {
    const r = liRng(seed);
    const W = 1200,
      H = height;
    const paths = [],
      nodes = [],
      leaves = [];
    /* the light-ground bands grow fuller: more colonies, deeper branching and small leaf nodes along the stems;
       the dark band keeps its original, sparser setting */
    const lush = !dark;
    const cfg = lush ? {
      colonies: 11,
      hyphae: 2,
      maxDepth: 4,
      minLen: 15,
      branchP: 0.5,
      shrink: 0.62,
      endNode: 0.5,
      grow: 1.2
    } : {
      colonies: 6,
      hyphae: 2,
      maxDepth: 4,
      minLen: 16,
      branchP: 0.5,
      shrink: 0.6,
      endNode: 0.7
    };
    const grow = (x, y, ang, len, depth) => {
      if (depth > cfg.maxDepth || len < cfg.minLen) return;
      const entry = {
        d: '',
        depth
      };
      paths.push(entry);
      const steps = 3 + Math.floor(r() * 3);
      let d = `M${x.toFixed(1)} ${y.toFixed(1)}`;
      let cx = x,
        cy = y,
        a = ang;
      for (let i = 0; i < steps; i++) {
        a += (r() - 0.5) * (lush ? 0.6 : 0.9);
        const nx = cx + Math.cos(a) * len / steps,
          ny = cy + Math.sin(a) * len / steps;
        const mx = (cx + nx) / 2 + (r() - 0.5) * 8,
          my = (cy + ny) / 2 + (r() - 0.5) * 8;
        d += ` Q${mx.toFixed(1)} ${my.toFixed(1)} ${nx.toFixed(1)} ${ny.toFixed(1)}`;
        cx = nx;
        cy = ny;
        if (r() < cfg.branchP) grow(cx, cy, a + (r() < 0.5 ? -1 : 1) * (lush ? 0.35 + r() * 0.5 : 0.5 + r() * 0.7), len * cfg.shrink, depth + 1);
        if (lush && r() < (depth ? 0.12 : 0.07)) {
          /* alternate leaves, one each side of the stem, tilted forward along its direction */
          const side = (i + depth) % 2 ? 1 : -1;
          leaves.push({
            x: cx,
            y: cy,
            rot: a + side * (Math.PI / 2 - 0.5 + (r() - 0.5) * 0.35),
            s: 0.58 + r() * 0.3 - depth * 0.04,
            depth
          });
        }
      }
      entry.d = d;
      if (r() < cfg.endNode) {
        if (lush) leaves.push({
          x: cx,
          y: cy,
          rot: a,
          s: 0.75 + r() * 0.35 - depth * 0.05,
          depth
        });else nodes.push({
          x: cx,
          y: cy,
          r: 1.3 + r() * 2.2,
          depth
        });
      }
    };
    const colonies = cfg.colonies;
    for (let i = 0; i < colonies; i++) {
      const x0 = W / colonies * (i + 0.5) + (r() - 0.5) * 90,
        y0 = H / 2 + (r() - 0.5) * 24;
      const gm = cfg.grow || 1;
      /* on the light grounds the main stems sweep sideways in long, gentle arcs (vines, not diagonals), one
         heading each way from every colony; the dark band keeps its free direction */
      const sx = lush ? (i % 2 ? Math.PI : 0) + (r() - 0.5) * 0.8 : r() * Math.PI * 2;
      const sy = lush ? (i % 2 ? 0 : Math.PI) + (r() - 0.5) * 0.8 : r() * Math.PI * 2;
      grow(x0, y0, sx, (110 + r() * 60) * gm, 0);
      grow(x0, y0, sy, (90 + r() * 60) * gm, 0);
      if (cfg.hyphae > 2) grow(x0, y0, r() * Math.PI * 2, (80 + r() * 60) * gm, 0);
    }
    return {
      paths,
      nodes,
      leaves
    };
  }, [seed, height, dark]);
  return /*#__PURE__*/React.createElement("svg", {
    ref: ref,
    className: `li-myc${dark ? ' dark' : ''}`,
    viewBox: `0 0 1200 ${height}`,
    preserveAspectRatio: "xMidYMid slice",
    "aria-hidden": "true",
    style: {
      height
    }
  }, paths.map((p, i) => /*#__PURE__*/React.createElement("path", {
    key: i,
    d: p.d,
    pathLength: "1",
    style: {
      transitionDelay: dark ? `${Math.min(i * 6, 450)}ms` : `${p.depth * 200 + i % 12 * 20}ms`,
      strokeWidth: Math.max(dark ? 0.6 : 0.9, (dark ? 1.5 : 2) - p.depth * (dark ? 0.25 : 0.3))
    }
  })), nodes.map((n, i) => /*#__PURE__*/React.createElement("circle", {
    key: i,
    cx: n.x,
    cy: n.y,
    r: n.r,
    style: {
      transitionDelay: `${Math.min(350 + i * 6, 800)}ms`
    }
  })), leaves.map((l, i) => /*#__PURE__*/React.createElement("path", {
    key: 'l' + i,
    className: "leaf",
    d: LI_BODHI,
    style: {
      '--t': `translate(${l.x.toFixed(1)}px, ${l.y.toFixed(1)}px) rotate(${((l.rot + Math.PI / 2) * 180 / Math.PI).toFixed(0)}deg)`,
      '--s': l.s.toFixed(2),
      transitionDelay: `${800 + l.depth * 200 + i % 10 * 12}ms`
    }
  })));
};

/* ─── Chrome ─────────────────────────────────────────────────────────── */
const LINav = () => {
  const [scrolled, setScrolled] = React.useState(false);
  React.useEffect(() => {
    const on = () => setScrolled(window.scrollY > 8);
    on();
    window.addEventListener('scroll', on);
    return () => window.removeEventListener('scroll', on);
  }, []);
  return /*#__PURE__*/React.createElement("nav", {
    className: `nav cph-nav${scrolled ? ' scrolled' : ''}`
  }, /*#__PURE__*/React.createElement("button", {
    className: "nav-brand li-brand",
    type: "button",
    onClick: () => window.scrollTo({
      top: 0,
      behavior: 'smooth'
    }),
    style: {
      background: 'transparent',
      border: 'none',
      cursor: 'pointer',
      padding: 0
    }
  }, /*#__PURE__*/React.createElement(LIMark, {
    size: 34
  }), /*#__PURE__*/React.createElement("span", {
    className: "nav-brand-text"
  }, "Living Intelligence")), /*#__PURE__*/React.createElement("div", {
    className: "nav-links"
  }, /*#__PURE__*/React.createElement("button", {
    className: "nav-cta",
    type: "button",
    onClick: () => window.open(LI_JOIN_URL, '_blank')
  }, LI_CTA)));
};
const LIFooter = ({
  onJump
}) => /*#__PURE__*/React.createElement("footer", {
  className: "footer"
}, /*#__PURE__*/React.createElement("div", {
  className: "footer-inner"
}, /*#__PURE__*/React.createElement("div", {
  className: "footer-brand"
}, /*#__PURE__*/React.createElement("span", {
  className: "li-mark-foot"
}, /*#__PURE__*/React.createElement(LIMark, {
  size: 38
})), /*#__PURE__*/React.createElement("div", {
  className: "footer-brand-text"
}, "Living Intelligence"), /*#__PURE__*/React.createElement("div", {
  className: "footer-tagline"
}, "Coevolution for a Regenerative Future"), /*#__PURE__*/React.createElement("a", {
  href: LI_JOIN_URL,
  target: "_blank",
  rel: "noreferrer",
  className: "footer-join-btn"
}, LI_CTA)), /*#__PURE__*/React.createElement("div", {
  className: "footer-col"
}, /*#__PURE__*/React.createElement("h6", null, "On this page"), LI_SECTIONS.map(s => /*#__PURE__*/React.createElement("a", {
  key: s.id,
  href: `#${s.id}`,
  onClick: e => {
    e.preventDefault();
    onJump(s.id);
  }
}, s.label))), /*#__PURE__*/React.createElement("div", {
  className: "footer-col"
}, /*#__PURE__*/React.createElement("h6", null, "Where this comes from"), /*#__PURE__*/React.createElement("a", {
  href: "https://audax.earth/#camp",
  target: "_blank",
  rel: "noreferrer"
}, "Camp Audax"))), /*#__PURE__*/React.createElement("div", {
  className: "footer-bottom"
}, /*#__PURE__*/React.createElement("span", null, "\xA9 2026 \xB7 A narrative grown from Camp Audax, open to any organization building toward it."), /*#__PURE__*/React.createElement("span", null, "For the biosphere, for people and for the machines we are learning to live with.")));

/* Nodes and ink instead of a photograph. Same orchestration as the Camp hero
   (headline types in, the clause writes itself, the meta line types), on top of
   the living canvas. */
const LIHero = ({
  children
}) => {
  const ref = React.useRef(null);
  const washRef = React.useRef(null);
  const netRef = React.useRef(null);
  const copyRef = React.useRef(null);
  const liveRef = React.useRef(true);
  useLivingCanvas(ref, washRef, netRef);
  React.useEffect(() => {
    const el = ref.current;
    if (!el || !('IntersectionObserver' in window)) return undefined;
    const io = new IntersectionObserver(([e]) => {
      liveRef.current = e.isIntersecting;
    }, {
      threshold: 0.15
    });
    io.observe(el);
    return () => io.disconnect();
  }, []);
  React.useEffect(() => {
    const root = copyRef.current;
    const hero = ref.current;
    if (!root) return undefined;
    const q = s => root.querySelector(s);
    if (cphReduced()) {
      if (hero) hero.classList.add('cph-lit');
      root.querySelectorAll('.cph-c, .cph-rise').forEach(e => e.classList.add('cph-in'));
      cphRotate(q('.cph-rot'), LI_ROTATION);
      return undefined;
    }
    const h1 = q('h1');
    cphSplit(h1);
    [q('.eyebrow'), q('.lede'), q('.hero-ctas')].forEach(cphArm);
    const meta1 = q('.cph-hero-meta');
    const meta2 = q('.cph-hero-meta-2');
    const restore = [meta1, meta2].filter(Boolean).map(el => [el, el.innerHTML]);
    void root.offsetHeight;
    if (hero) hero.classList.add('cph-lit');
    cphRise(q('.eyebrow'), 260);
    const after = cphStaggerChars(h1, 420, 17);
    h1.classList.add('cph-in');
    cphRise(q('.lede'), after + 80);
    cphType(meta1, after + 320, 900, () => cphType(meta2, 140, 900));
    cphRise(q('.hero-ctas'), after + 1500);
    const stopRot = cphRotate(q('.cph-rot'), LI_ROTATION, after + 300, () => liveRef.current);
    const bail = setTimeout(() => {
      if (hero) hero.classList.add('cph-lit');
      root.querySelectorAll('.cph-c, .cph-rise').forEach(e => e.classList.add('cph-in'));
      restore.forEach(([el, html]) => {
        if (el._cphFinish) el._cphFinish();else if (!el.textContent.trim()) el.innerHTML = html;
        el.classList.remove('cph-typing');
      });
    }, 12000);
    return () => {
      clearTimeout(bail);
      if (stopRot) stopRot();
      restore.forEach(([el]) => {
        clearTimeout(el._cphStart);
        clearInterval(el._cphTimer);
      });
    };
  }, []);
  return /*#__PURE__*/React.createElement("section", {
    className: "cph-hero li-hero",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "cph-stage li-stage"
  }, /*#__PURE__*/React.createElement("canvas", {
    className: "lh-wash",
    ref: washRef
  }), /*#__PURE__*/React.createElement("canvas", {
    className: "lh-net",
    ref: netRef
  })), /*#__PURE__*/React.createElement("div", {
    className: "cph-veil li-veil"
  }), /*#__PURE__*/React.createElement(CampGrain, null), /*#__PURE__*/React.createElement(CampTear, {
    image: ART.drift,
    edge: "bottom",
    deep: true
  }), /*#__PURE__*/React.createElement("div", {
    className: "container cph-hero-copy",
    ref: copyRef
  }, children));
};
const LILogoBar = () => /*#__PURE__*/React.createElement("div", {
  className: "cph-logobar"
}, /*#__PURE__*/React.createElement("div", {
  className: "container"
}, /*#__PURE__*/React.createElement("p", {
  className: "cph-logobar-label"
}, "Co-created by"), /*#__PURE__*/React.createElement("div", {
  className: "cph-logobar-row"
}, /*#__PURE__*/React.createElement("a", {
  className: "cph-logobar-item",
  href: "https://coherence.tv/",
  target: "_blank",
  rel: "noreferrer"
}, /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-full",
  src: "assets/co-creators/coherence-company.png",
  alt: "The Coherence Company"
})), /*#__PURE__*/React.createElement("a", {
  className: "cph-logobar-item",
  href: "https://geoship.is/",
  target: "_blank",
  rel: "noreferrer"
}, /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-mark",
  src: "assets/co-creators/geoship-mark.svg",
  alt: ""
}), /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-word",
  src: "assets/co-creators/geoship-wordmark.svg",
  alt: "Geoship"
})), /*#__PURE__*/React.createElement("a", {
  className: "cph-logobar-item cph-logobar-item-tight",
  href: "https://www.modernancients.com/",
  target: "_blank",
  rel: "noreferrer"
}, /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-mark-ma",
  src: "assets/co-creators/modern-ancients-mark.png",
  alt: ""
}), /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-word-ma",
  src: "assets/co-creators/modern-ancients-wordmark.png",
  alt: "Modern Ancients"
}))), /*#__PURE__*/React.createElement("div", {
  className: "cph-logobar-row li-logobar-row2"
}, /*#__PURE__*/React.createElement("a", {
  className: "cph-logobar-item li-logobar-alinea",
  href: "https://alinea.institute",
  target: "_blank",
  rel: "noreferrer",
  "aria-label": "Alinea Institute"
}, /*#__PURE__*/React.createElement("img", {
  className: "li-alinea-mark",
  src: "assets/co-creators/alinea-mark.png",
  alt: ""
}), /*#__PURE__*/React.createElement("img", {
  className: "li-alinea-word",
  src: "assets/co-creators/alinea-word.png",
  alt: "Alinea"
})), /*#__PURE__*/React.createElement("a", {
  className: "cph-logobar-item",
  href: "https://themetalayer.org",
  target: "_blank",
  rel: "noreferrer"
}, /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-mark-mli",
  src: "assets/co-creators/metalayer-mark.png",
  alt: ""
}), /*#__PURE__*/React.createElement("img", {
  className: "cph-logobar-word-mli",
  src: "assets/co-creators/metalayer-wordmark.png",
  alt: "Meta-Layer Initiative"
})))));

/* ─── The page ─────────────────────────────────────────────────────────── */
const PageLiving = () => {
  const [active, setActive] = React.useState(LI_SECTIONS[0].id);
  React.useEffect(() => {
    const els = LI_SECTIONS.map(s => document.getElementById(s.id)).filter(Boolean);
    if (!els.length) return undefined;
    const on = () => {
      const line = 140;
      let cur = els[0].id;
      els.forEach(el => {
        if (el.getBoundingClientRect().top <= line) cur = el.id;
      });
      setActive(cur);
    };
    on();
    window.addEventListener('scroll', on, {
      passive: true
    });
    return () => window.removeEventListener('scroll', on);
  }, []);
  React.useEffect(() => {
    if (window.lucide) window.lucide.createIcons();
  });
  const jump = id => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({
      behavior: 'smooth',
      block: 'start'
    });
    if (window.history && window.history.replaceState) window.history.replaceState(null, '', `#living-intelligence/${id}`);
  };
  const anchor = {
    scrollMarginTop: 78
  };
  return /*#__PURE__*/React.createElement("div", {
    className: "li-page"
  }, /*#__PURE__*/React.createElement(LINav, null), /*#__PURE__*/React.createElement(LICampSignposts, {
    active: active,
    onJump: jump
  }), /*#__PURE__*/React.createElement(LIHero, null, /*#__PURE__*/React.createElement("div", {
    className: "hero-inner",
    style: {
      maxWidth: 880
    }
  }, /*#__PURE__*/React.createElement("h1", {
    className: "display lg"
  }, /*#__PURE__*/React.createElement("span", {
    className: "li-lead"
  }, "People, the Biosphere and AI,"), /*#__PURE__*/React.createElement("span", {
    className: "cph-rot cph-nosplit",
    "aria-hidden": "true"
  }), /*#__PURE__*/React.createElement("span", {
    className: "cph-sr cph-nosplit"
  }, LI_ROTATION[0])), /*#__PURE__*/React.createElement("p", {
    className: "lede",
    style: {
      maxWidth: 640
    }
  }, "A shared north star for the relationship between the living world, human beings and artificial/augmented intelligence, offered by people passionate about this work - designing & testing in the open."), /*#__PURE__*/React.createElement("p", {
    className: "cph-hero-meta"
  }, "A consortium narrative\xA0 \xB7\xA0 ", /*#__PURE__*/React.createElement("span", {
    className: "cph-date"
  }, "Coevolution for a Regenerative Future")), /*#__PURE__*/React.createElement("p", {
    className: "cph-hero-meta cph-hero-meta-2"
  }, "Emerging from ", /*#__PURE__*/React.createElement("a", {
    href: LI_JOIN_URL,
    target: "_blank",
    rel: "noreferrer"
  }, "Camp Audax"), " \xB7 open to all organizations building this vision"), /*#__PURE__*/React.createElement("div", {
    className: "hero-ctas",
    style: {
      marginTop: 36
    }
  }, /*#__PURE__*/React.createElement(Button, {
    size: "lg",
    variant: "join",
    icon: "arrow-down",
    onClick: () => jump('relationship')
  }, "Read the north star")))), /*#__PURE__*/React.createElement(LILogoBar, null), /*#__PURE__*/React.createElement(LICampWhyCome, {
    items: LI_WHY_COME
  }), /*#__PURE__*/React.createElement(Mycelium, {
    seed: 11,
    height: 190
  }), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "relationship",
    style: {
      ...anchor,
      paddingBottom: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "01 \xB7 The relationship"), "How the biosphere, people and AI relate ", /*#__PURE__*/React.createElement("em", null, "is a design choice.")), /*#__PURE__*/React.createElement(CampAside, {
    shot: "owl",
    alt: "An owl perched on a tree in a forest",
    ratio: "4 / 5",
    style: {
      marginTop: 12
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Alliances and movements around the world are shaping the future of AI: human-centered AI coalitions, safety researchers, regenerative and impact networks, labor and faith communities, open-source builders. They share an instinct that people, communities and living systems deserve a real say over the technologies that affect them. Concern about concentrated power, surveillance, lost livelihoods and strain on the biosphere motivates much of this work and each concern deserves a serious answer."), /*#__PURE__*/React.createElement("p", null, "This page adds one question that sits beside all of those efforts: what vision of interrelationship of the biosphere, people and AI do we want to grow into? If far more capable systems arrive (which appears likely) stewardship of these systems is one part of a larger picture. That picture also holds what those systems owe the living world, what groups of people and individuals owe each other, and what healthy coevolution looks like as capability grows. A durable, mutually flourishing relationship among all three components gives every alliance a positive field to build within, on any timeline."))), /*#__PURE__*/React.createElement(CampKicker, {
    top: 56,
    bottom: 8
  }, "Three ways to name the field"), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 24
    }
  }, /*#__PURE__*/React.createElement("p", null, "Each framing brings a different sense of the field into focus: the people AI serves, the potential synergies between humans and AI, and the Biosphere that sustains them both. Read in order, each frame takes in more of the field than the one before.")), /*#__PURE__*/React.createElement("table", {
    className: "mini-matrix"
  }, /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", null, /*#__PURE__*/React.createElement("th", null, "The framing"), /*#__PURE__*/React.createElement("th", null, "What it brings into view"))), /*#__PURE__*/React.createElement("tbody", null, LI_HYPHEN.map(([f, v]) => /*#__PURE__*/React.createElement("tr", {
    key: f
  }, /*#__PURE__*/React.createElement("th", null, f), /*#__PURE__*/React.createElement("td", null, v))))), /*#__PURE__*/React.createElement(CampQuote, null, "Our relationship with the biosphere is decided in the design. ", /*#__PURE__*/React.createElement("em", null, "The time to decide it is early.")))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "why",
    style: {
      ...anchor,
      paddingBottom: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "02 \xB7 Why"), "The tools we build become the society we ", /*#__PURE__*/React.createElement("span", {
    className: "cph-keep"
  }, "live in."), " ", /*#__PURE__*/React.createElement("em", null, "So does the way we tend the living world.")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "The early web was built by people who wanted openness and connection and it delivered both. It also delivered concentrated platforms, opaque recommendation systems and incentives that emerged by accident. Each choice looked reasonable at the time and together they accumulated until they became the water we swim in. One of the internet\u2019s own founders has said as much: the people building it had no idea what would follow."), /*#__PURE__*/React.createElement("p", null, "AI is arriving the same way, only faster and at greater scale. The defaults being set now, what these systems optimize for, whom they answer to, what they count as value and what they are allowed to leave out, will be very hard to change once they ship. The living world is usually the first thing left out.")), /*#__PURE__*/React.createElement(CampQuote, null, "Whatever we leave out of the design, ", /*#__PURE__*/React.createElement("em", null, "we leave out of the future.")), /*#__PURE__*/React.createElement(CampKicker, {
    top: 56,
    bottom: 8
  }, "What we are asking instead"), /*#__PURE__*/React.createElement(CampAside, {
    shot: "indoor-plate",
    alt: "Two people in conversation in a forest clearing",
    ratio: "4 / 3",
    caption: "Slow questions, asked early.",
    style: {
      marginTop: 12
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Before the architecture hardens, we would like to ask what should be true of the whole ecosystem that emerges as products, models and policies come together."), /*#__PURE__*/React.createElement("p", null, "So we start with the destination. We describe the properties we would consciously choose, in language specific enough to build toward and invite builders, stewards, funders and policy makers to test their work against the same shared reference."), /*#__PURE__*/React.createElement("p", null, "We call these the Desirable Properties. Together they form a north star, offered lightly and open to challenge."))))), /*#__PURE__*/React.createElement("section", {
    className: "section li-dark li-triad-sec",
    id: "triad",
    style: {
      ...anchor,
      paddingTop: 118
    }
  }, /*#__PURE__*/React.createElement(CampTear, {
    image: ART.spray,
    edge: "top",
    ground: "var(--surface-parchment)",
    flip: true
  }), /*#__PURE__*/React.createElement("div", {
    className: "container li-triad-head"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "03 \xB7 The triad"), "Where the three meet, ", /*#__PURE__*/React.createElement("em", null, "a regenerative future grows.")), /*#__PURE__*/React.createElement("p", {
    className: "li-tri-q"
  }, "What should be true of the relationship between the biosphere, human beings and AI?"), /*#__PURE__*/React.createElement("p", {
    className: "li-tri-read"
  }, "How to read it: five qualities orient each circle, each overlap names what two intelligences share and the center holds the aim they serve together.")), /*#__PURE__*/React.createElement("div", {
    className: "container li-triad-stage"
  }, /*#__PURE__*/React.createElement(TriadDiagram, null)), /*#__PURE__*/React.createElement("p", {
    className: "li-tri-note"
  }, "A second Desirable Properties process, modeled on the Meta-Layer approach, defines what is desirable where living systems, people and AI intersect."), /*#__PURE__*/React.createElement(CampTear, {
    image: ART.crest,
    edge: "bottom",
    ground: "var(--surface-parchment)"
  })), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "intelligences",
    style: {
      ...anchor,
      paddingBottom: 0,
      paddingTop: 84
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "04 \xB7 Three intelligences"), "Each holds something ", /*#__PURE__*/React.createElement("em", null, "the others need.")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 40
    }
  }, /*#__PURE__*/React.createElement("p", null, "Each of these three shapes the other two and each is right about something the others miss. The list of properties comes from all three at once. Written by any one of them alone, it becomes a wish.")), /*#__PURE__*/React.createElement(LICampPersonaSlider, {
    profiles: LI_TRIAD
  }), /*#__PURE__*/React.createElement(CampQuote, null, "Each is right about something. ", /*#__PURE__*/React.createElement("em", null, "Holding the whole takes all three.")))), /*#__PURE__*/React.createElement(LICampBand, {
    shot: "canopy",
    kicker: "Starting points",
    label: "Open threads we are exploring",
    tearTop: ART.spray,
    tearGroundTop: "var(--surface-parchment)",
    tear: ART.crest,
    tearGround: "var(--li-dark-ground)",
    rate: 0.18
  }), /*#__PURE__*/React.createElement("section", {
    className: "section li-dark li-precedent",
    id: "questions",
    style: {
      ...anchor
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "05 \xB7 The questions we hold"), "Where our inquiry ", /*#__PURE__*/React.createElement("em", null, "begins.")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 40
    }
  }, /*#__PURE__*/React.createElement("p", null, "These are some initial questions shaping our field of inquiry. Each grows richer with more voices & perspective around it. We want to understand how to move more deeply into this questioning.")), /*#__PURE__*/React.createElement(LICampDiptych, {
    items: LI_QUESTION_ITEMS,
    label: "Question",
    compact: true
  })), /*#__PURE__*/React.createElement(Mycelium, {
    seed: 23,
    height: 190,
    dark: true
  }), /*#__PURE__*/React.createElement(CampTear, {
    image: ART.crest,
    edge: "bottom",
    ground: "var(--surface-parchment)",
    deep: true
  })), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "stool",
    style: {
      ...anchor,
      paddingBottom: 0,
      paddingTop: 84
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "06 \xB7 Beyond the tools"), "Three things carry the transition: ", /*#__PURE__*/React.createElement("em", null, "tools, mindsets and equity.")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "Technology and architecture are the first. Architectural solutions answer architectural problems, so this reaches past tools to the structure of the whole system. The second is the maturity to use it well and the third is a future that is fair, free and flourishing for everyone. Each supports the other two, so the properties in this list reach into all three.")), /*#__PURE__*/React.createElement(CampCascade, {
    className: "insight-grid",
    style: {
      marginTop: 36
    }
  }, LI_STOOL.map(([h, p, label]) => /*#__PURE__*/React.createElement("article", {
    key: h,
    className: "insight-card"
  }, /*#__PURE__*/React.createElement("h4", null, h, ". ", p), /*#__PURE__*/React.createElement("p", {
    style: {
      marginTop: 10,
      fontFamily: 'var(--font-sans)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.14em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)'
    }
  }, label)))), /*#__PURE__*/React.createElement(CampAside, {
    flip: true,
    shot: "delta",
    alt: "Aerial view of a river delta, its channels fanning out in bands of color",
    ratio: "1 / 1",
    style: {
      marginTop: 40
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "People in this network work where tools, mindsets and equity meet. Ecological engineers feed the biosphere\u2019s own data into AI systems. Storytellers help regenerative and impact movements see AI as a powerful ally. Builders keep the tools open enough that a founder in Palo Alto and a student anywhere in the world can pick them up and do something wild with them. Cultural maturity, in the sense of ", /*#__PURE__*/React.createElement("a", {
    href: "https://docs.google.com/document/d/150BbAGwigiNVx3-dYSZRuQ81tc2n5fQhZ9xWobTraa4/edit?usp=sharing",
    target: "_blank",
    rel: "noreferrer",
    style: {
      color: 'var(--forest-700)'
    }
  }, "Pavel Luksha\u2019s work on planetary adulthood"), ", ties these threads together."), /*#__PURE__*/React.createElement("p", null, "One idea from the wider conversation, sometimes called ecosystemic singularity, imagines the point where the whole living system, people, machines and biosphere included, begins to think together. Coevolution describes the road toward it."))))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "properties",
    style: {
      ...anchor,
      paddingBottom: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "07 \xB7 Desirable Properties"), "What would have to be true ", /*#__PURE__*/React.createElement("em", null, "for this to be desirable?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 32
    }
  }, /*#__PURE__*/React.createElement("p", null, "A Desirable Property is a condition, specific enough to build toward and specific enough to disagree about. It sits between a value, such as regeneration and a requirement, such as \u201Cthe system must\u2026\u201D and it is the step most projects skip on the way from one to the other.")), /*#__PURE__*/React.createElement(CampKicker, null, "A value says. A property asks."), /*#__PURE__*/React.createElement("table", {
    className: "mini-matrix"
  }, /*#__PURE__*/React.createElement("thead", null, /*#__PURE__*/React.createElement("tr", null, /*#__PURE__*/React.createElement("th", null, "The value"), /*#__PURE__*/React.createElement("th", null, "The property"))), /*#__PURE__*/React.createElement("tbody", null, LI_VALUE_PROPERTY.map(([v, p]) => /*#__PURE__*/React.createElement("tr", {
    key: v
  }, /*#__PURE__*/React.createElement("th", null, v), /*#__PURE__*/React.createElement("td", null, p))))), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      color: 'var(--ink-500)',
      margin: '20px 0 0',
      maxWidth: 760
    }
  }, "These are candidates for discussion. Each needs an explanation, a practical example and an honest account of the tensions it creates."), /*#__PURE__*/React.createElement(CampAside, {
    shot: "roots-tall",
    alt: "Moss-covered tree roots and ferns on the forest floor",
    ratio: "4 / 5",
    style: {
      marginTop: 64
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(CampKicker, {
    top: 0,
    bottom: 8
  }, "How each property gets written"), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Each property works like a small lab. Three to five subject-matter experts anchor it, joined by practitioners and community voices who bring lived evidence. A lab produces an explanation, a practical example, an honest account of the tensions and a list of the projects already advancing the property."), /*#__PURE__*/React.createElement("p", null, "Every property has its own collaboration page where anyone can propose a revision and the group adjudicates what enters the next version. Revisions arrive as patches, each traceable to the person or the conversation it came from.")), /*#__PURE__*/React.createElement(CampKicker, {
    top: 44,
    bottom: 8
  }, "Two layers, side by side"), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "The ", /*#__PURE__*/React.createElement("a", {
    href: "https://themetalayer.org",
    target: "_blank",
    rel: "noreferrer",
    style: {
      color: 'var(--forest-700)'
    }
  }, "Meta-Layer Initiative"), " maintains a canonical set of twenty-three properties for digital and social coordination systems, among them agency, privacy, trust and interoperability. The Biosphere\u2013Human\u2013AI process forms a second layer beside it, a parallel exercise with the same method and the biosphere at its center of gravity. A third set covering federation and governance may follow. Expect roughly five to fifteen properties in each new set.")))), /*#__PURE__*/React.createElement("div", {
    style: {
      ...campNote,
      marginTop: 44
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: campNoteH6
  }, "Read the method in full"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 15,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--forest-900)',
      margin: '0 0 14px'
    }
  }, "The Desirable Properties approach comes from Daveed Benjamin\u2019s work through a Meta-Layer lens. His two recommendations set out the method we are extending: a North Star Analysis over four to six weeks and an exploration of the words we start from."), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 15,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--forest-900)',
      margin: 0
    }
  }, /*#__PURE__*/React.createElement("a", {
    href: "https://prohumannatureai.com/r/north-star",
    target: "_blank",
    rel: "noreferrer",
    style: {
      color: 'var(--forest-700)'
    }
  }, "The North Star Analysis"), ' · ', /*#__PURE__*/React.createElement("a", {
    href: "https://prohumannatureai.com/r/semantic",
    target: "_blank",
    rel: "noreferrer",
    style: {
      color: 'var(--forest-700)'
    }
  }, "Exploring the words"), ' · ', /*#__PURE__*/React.createElement("a", {
    href: "https://prohumannatureai.com/deepi",
    target: "_blank",
    rel: "noreferrer",
    style: {
      color: 'var(--forest-700)'
    }
  }, "Talk with Deepi, the North Star guide"))), /*#__PURE__*/React.createElement(CampQuote, null, "A shared vision becomes a north star ", /*#__PURE__*/React.createElement("em", null, "when people steer by it.")))), /*#__PURE__*/React.createElement(LICampJoinBand, {
    shot: "carpet",
    pos: "center 28%",
    tearTop: ART.wave,
    tearGroundTop: "var(--surface-parchment)",
    tear: ART.crest,
    tearGround: "var(--surface-parchment)"
  }, "Every future starts as a conversation. ", /*#__PURE__*/React.createElement("em", null, "Join ours.")), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "build",
    style: {
      ...anchor,
      paddingBottom: 0,
      paddingTop: 24
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "08 \xB7 From design to build"), "From Desirable Properties ", /*#__PURE__*/React.createElement("em", null, "to a working system.")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 32
    }
  }, /*#__PURE__*/React.createElement("p", null, "A list of properties gains force when builders can use it. The method runs in seven steps and every second step belongs to people. AI drafts at speed and people decide what the drafts are worth.")), /*#__PURE__*/React.createElement(LISteps, {
    steps: LI_STEPS
  }), /*#__PURE__*/React.createElement(CampQuote, null, "A property earns its place ", /*#__PURE__*/React.createElement("em", null, "the day someone builds with it.")))), /*#__PURE__*/React.createElement(Mycelium, {
    seed: 37,
    height: 180
  }), /*#__PURE__*/React.createElement("section", {
    className: "section",
    id: "field",
    style: {
      ...anchor,
      paddingBottom: 0,
      paddingTop: 24
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(LICampInk, {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "09 \xB7 Weaving the field"), "Many tools. ", /*#__PURE__*/React.createElement("em", null, "One field.")), /*#__PURE__*/React.createElement(CampAside, {
    flip: true,
    shot: "forest-gathering",
    alt: "People gathered among trees at a forest camp, some seated on hay bales and others standing in conversation",
    ratio: "1 / 1",
    style: {
      marginTop: 12
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Teams across this network are building coordination tools, trust signals, matchmaking engines and community platforms. Each speaks to a different audience and the field gains from every one of them. The task is to federate them into an environment where they interoperate as needed, so that any community can work through whichever tools fit it. Together these tools become working infrastructure for collective intelligence: they help communities think, decide and learn together, which prepares all of us to work well with far more capable AI.")), /*#__PURE__*/React.createElement(CampKicker, {
    top: 40,
    bottom: 8
  }, "Emergence guides the work"), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Our work follows the way living systems organize. Order arises from many small relationships: one team shares what it has learned, another builds on it, and patterns take shape that no one planned in advance. We pay attention to what is already forming and support it, the way a gardener tends what wants to grow.")), /*#__PURE__*/React.createElement(CampKicker, {
    top: 40,
    bottom: 8
  }, "Resonance draws us together"), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Organizations and individuals whose purposes align recognize one another. Resonance brings them together, and collaborations form around shared questions and complementary gifts. A living map of the field helps these connections find each other sooner, and each one strengthens the whole.")))), /*#__PURE__*/React.createElement(CampKicker, {
    top: 56,
    bottom: 8
  }, "How a forest shares"), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "A forest moves water, sugar and signals through a web of roots and fungi, and every species contributes what it does best. Three layers give the field the same shape.")), /*#__PURE__*/React.createElement(CampCascade, {
    className: "insight-grid",
    style: {
      marginTop: 24
    }
  }, LI_FOREST_LAYERS.map(([h, p, label]) => /*#__PURE__*/React.createElement("article", {
    key: h,
    className: "insight-card"
  }, /*#__PURE__*/React.createElement("h4", null, h, ". ", p), /*#__PURE__*/React.createElement("p", {
    style: {
      marginTop: 10,
      fontFamily: 'var(--font-sans)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.14em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)'
    }
  }, label)))), /*#__PURE__*/React.createElement(CampAside, {
    shot: "wing",
    alt: "A butterfly wing up close, teal scales with orange and cream markings",
    ratio: "3 / 4",
    style: {
      marginTop: 32
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(CampKicker, {
    top: 0,
    bottom: 8
  }, "Agreements that keep it fair"), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Reciprocity needs terms: how contributions are credited, how intellectual property and data rights are shared and what happens when one team expands a product while another steps back from a layer a partner covers better. Trade-offs of that kind, investing here and divesting there, are the working substance of a co-development agreement.")), /*#__PURE__*/React.createElement(CampKicker, {
    top: 44,
    bottom: 8
  }, "A map that keeps itself current"), /*#__PURE__*/React.createElement("div", {
    className: "q-body"
  }, /*#__PURE__*/React.createElement("p", null, "Each organization shares what it can publicly: papers, websites, programs. A community AI reads it all into a graph database and answers questions such as which collaborations would serve the most properties and remain untried. A link is enough to add a new program and a notification follows when a member\u2019s site changes. An ecosystem-weaving agent grows out of this map."), /*#__PURE__*/React.createElement("p", null, "Agents take a seat at this table too. Each person may bring their own agent and the field needs norms for how agents relate to their people, to one another and to the living world.")))), /*#__PURE__*/React.createElement(CampQuote, null, "The North Star names the destination. ", /*#__PURE__*/React.createElement("em", null, "The map reveals the travelers.")))), /*#__PURE__*/React.createElement(LICampBand, {
    shot: "tents",
    kicker: "Camp Navarro \xB7 15\u201318 October 2026",
    label: "Where the work begins",
    featured: true,
    cta: {
      label: 'Visit the Camp Audax page',
      href: LI_JOIN_URL
    },
    tearTop: ART.crest,
    tearGroundTop: "var(--surface-parchment)",
    tear: ART.spray,
    tearGround: "var(--surface-parchment)",
    rate: 0.16
  }), /*#__PURE__*/React.createElement("section", {
    className: "section-tight",
    id: "loops",
    style: {
      ...anchor,
      paddingTop: 72,
      paddingBottom: 0
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(CampKicker, {
    top: 0,
    bottom: 8
  }, "Small loops first"), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "At the Gathering this October at Camp Navarro, CA, the aim is to execute three or four small OODA loops (observe, orient, decide, act) that carry select properties from idea to working prototype in days. The tooling makes that speed possible and small experiments give partners and grant makers something real to test."), /*#__PURE__*/React.createElement("p", null, "The reference itself works like a living book. A community AI turns an idea, a link or an uploaded document into a drafted submission and suggests where in the existing text it belongs. Submissions post as drafts and reach the book through the group\u2019s review.")))), /*#__PURE__*/React.createElement("section", {
    className: "section-tight",
    id: "calls",
    style: {
      ...anchor,
      paddingTop: 56,
      paddingBottom: 110
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(CampKicker, {
    bottom: 8
  }, "Meet us on a call"), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 24
    }
  }, /*#__PURE__*/React.createElement("p", null, "Join one of the next Camp Audax calls to meet the people involved and bring your questions. Pick whichever time suits you.")), /*#__PURE__*/React.createElement(LILumaCarousel, {
    ids: LI_LUMA_EVENTS
  }))), /*#__PURE__*/React.createElement(CampJoinBand, {
    shot: "trail",
    pos: "center 50%",
    tearTop: ART.wave,
    tearGroundTop: "var(--surface-parchment)",
    tear: ART.crest,
    tearGround: "var(--surface-parchment)"
  }, "Coevolve ", /*#__PURE__*/React.createElement("em", null, "with us.")), /*#__PURE__*/React.createElement("section", {
    className: "section-tight",
    id: "join",
    style: {
      ...anchor
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(CampKicker, {
    bottom: 8
  }, "Try it with your own AI"), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 24
    }
  }, /*#__PURE__*/React.createElement("p", null, "The quickest way in is to see how your own work meets the properties. Copy the prompt, paste it into any assistant, add a few sentences about what you do and read the first map it draws. If it sparks something, come and continue the conversation with us.")), /*#__PURE__*/React.createElement(LIPrompt, null), /*#__PURE__*/React.createElement("div", {
    className: "cph-apply",
    style: {
      marginTop: 56
    }
  }, /*#__PURE__*/React.createElement("h3", null, "An invitation, with no fixed membership"), /*#__PURE__*/React.createElement("p", null, "This list is incomplete on purpose. If a property is missing, a tension is understated, or a stronger example exists, that correction is exactly what this is for. Any organization already doing this work is part of the conversation, wherever its people are."), /*#__PURE__*/React.createElement("div", {
    className: "cph-apply-ctas"
  }, /*#__PURE__*/React.createElement(Button, {
    size: "lg",
    variant: "join",
    icon: "arrow-right",
    onClick: () => window.open(LI_JOIN_URL, '_blank')
  }, LI_CTA), LI_TELEGRAM_URL && /*#__PURE__*/React.createElement("a", {
    className: "btn btn-primary btn-lg",
    href: LI_TELEGRAM_URL,
    target: "_blank",
    rel: "noreferrer",
    style: {
      textDecoration: 'none'
    }
  }, /*#__PURE__*/React.createElement("span", null, "Join the Telegram group"), /*#__PURE__*/React.createElement("i", {
    "data-lucide": "send"
  })))))), /*#__PURE__*/React.createElement(LIFooter, {
    onJump: jump
  }));
};
window.PageLiving = PageLiving;