/* Generated from page-why.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
/* Audax OS site · Why? page (homepage)
   The argument only. Every "What ...?" section moved verbatim to
   page-map.jsx; "Where does this begin?" is parked pending the Labs page.
   Source copy: client brief (Audax OS — Why Page Revised Draft). */

const NODE_FIELD_BG = 'assets/accent-images/The_Gathering_httpss.mj.runC6iJti0L-5Q_abstract_horizontal_ca_89be8310-4193-4426-a643-b55ced9ca0f6_0.webp';
const Section = ({
  n,
  q,
  children,
  bg,
  narrow
}) => /*#__PURE__*/React.createElement("section", {
  className: "section",
  style: bg ? {
    background: bg
  } : null
}, /*#__PURE__*/React.createElement("div", {
  className: narrow ? 'container-narrow' : 'container'
}, /*#__PURE__*/React.createElement("h1", {
  className: "q-h1"
}, /*#__PURE__*/React.createElement("span", {
  className: "num"
}, n), /*#__PURE__*/React.createElement("span", {
  dangerouslySetInnerHTML: {
    __html: q
  }
})), /*#__PURE__*/React.createElement("div", {
  className: "q-body"
}, children)));
const PageWhy = ({
  onNav
}) => /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(LivingHero, {
  minHeight: "92vh"
}, /*#__PURE__*/React.createElement("div", {
  className: "hero-inner reveal",
  style: {
    maxWidth: 880
  }
}, /*#__PURE__*/React.createElement(Eyebrow, null, "For the age of humans and agents"), /*#__PURE__*/React.createElement("h1", {
  className: "display lg"
}, "How do we build ", /*#__PURE__*/React.createElement("em", null, "thriving", /*#__PURE__*/React.createElement("br", null), "organizations"), " in the age of", /*#__PURE__*/React.createElement("br", null), "humans and agents?"), /*#__PURE__*/React.createElement("p", {
  className: "lede",
  style: {
    maxWidth: 700,
    marginBottom: 16
  }
}, "The way we organize work was built for a different world. Remote work exposed the cracks. Fractional work widened them. AI agents now make them impossible to ignore."), /*#__PURE__*/React.createElement("p", {
  className: "lede",
  style: {
    maxWidth: 700,
    fontStyle: 'italic',
    marginBottom: 40
  }
}, "Audax OS is an open operating system for designing organizations where humans and AI agents work together coherently \u2014 across individuals, teams, organizations, organization families, and ecosystems."), /*#__PURE__*/React.createElement("div", {
  className: "hero-ctas"
}, /*#__PURE__*/React.createElement(Button, {
  variant: "join",
  size: "lg",
  icon: "arrow-right",
  onClick: () => window.open(JOIN_URL, '_blank')
}, "Join to co-create")))), /*#__PURE__*/React.createElement(Section, {
  n: "01 \xB7 The old model",
  q: "Why can\u2019t the old organizational forms hold <em>the new work?</em>"
}, /*#__PURE__*/React.createElement(ArtAside, {
  image: ART.orbHalf
}, /*#__PURE__*/React.createElement("p", null, "Most organizations still carry industrial assumptions. Work is divided into functions. Roles are fixed. Authority flows downward. Information climbs upward. Managers coordinate through meetings, reporting lines, and supervision. People are expected to belong mostly to one organization at a time."), /*#__PURE__*/React.createElement("p", null, "This model made sense when communication was slow, labor was physically concentrated, expertise was harder to access, and the organization could be managed as a relatively stable machine."), /*#__PURE__*/React.createElement("p", null, "But the conditions have changed. People now collaborate across time zones, projects, companies, networks, and communities. Work forms and dissolves around missions. Contributors enter and leave at different levels of commitment. AI agents can now remember, draft, coordinate, analyze, and act.")), /*#__PURE__*/React.createElement("p", {
  className: "lead"
}, "The old model is not simply inefficient. ", /*#__PURE__*/React.createElement("em", null, "It is misaligned"), " with the world now emerging."), /*#__PURE__*/React.createElement("div", {
  className: "contrast-grid",
  style: {
    marginTop: 16
  }
}, /*#__PURE__*/React.createElement("div", {
  className: "contrast-col"
}, /*#__PURE__*/React.createElement("h6", null, "Old organization"), /*#__PURE__*/React.createElement("h3", null, "Designed for the office."), /*#__PURE__*/React.createElement("ul", null, /*#__PURE__*/React.createElement("li", null, "Fixed roles"), /*#__PURE__*/React.createElement("li", null, "Full-time employment as default"), /*#__PURE__*/React.createElement("li", null, "Office-based context"), /*#__PURE__*/React.createElement("li", null, "Departmental silos"), /*#__PURE__*/React.createElement("li", null, "Managerial supervision"), /*#__PURE__*/React.createElement("li", null, "Tasks and reporting"), /*#__PURE__*/React.createElement("li", null, "Culture as an HR function"), /*#__PURE__*/React.createElement("li", null, "AI as a tool added later"))), /*#__PURE__*/React.createElement("div", {
  className: "contrast-col"
}, /*#__PURE__*/React.createElement("h6", null, "Emerging organization"), /*#__PURE__*/React.createElement("h3", null, "Designed for living systems."), /*#__PURE__*/React.createElement("ul", null, /*#__PURE__*/React.createElement("li", null, "Fluid contribution"), /*#__PURE__*/React.createElement("li", null, "Fractional participation"), /*#__PURE__*/React.createElement("li", null, "Distributed context"), /*#__PURE__*/React.createElement("li", null, "Mission-based cells"), /*#__PURE__*/React.createElement("li", null, "Shared accountability"), /*#__PURE__*/React.createElement("li", null, "Commitments and learning"), /*#__PURE__*/React.createElement("li", null, "Trust as infrastructure"), /*#__PURE__*/React.createElement("li", null, "AI agents as collaborators"))))), /*#__PURE__*/React.createElement(WashRule, {
  image: ART.spray,
  flip: true,
  from: "parchment",
  to: "paper"
}), /*#__PURE__*/React.createElement(Section, {
  n: "02 \xB7 AI agents",
  q: "Why do AI agents force <em>a complete rethink?</em>",
  bg: "var(--surface-paper)"
}, /*#__PURE__*/React.createElement("p", {
  className: "lead"
}, "AI is moving ", /*#__PURE__*/React.createElement("em", null, "from assistant to participant.")), /*#__PURE__*/React.createElement("p", null, "Agents can research, draft, synthesize, schedule, translate, analyze, remember, coordinate, and support workflows. Soon they will participate more directly in missions, handoffs, decisions, communication, and organizational memory."), /*#__PURE__*/React.createElement("p", null, "But agents cannot work well inside fog. They need:"), /*#__PURE__*/React.createElement("div", {
  className: "protocol-grid"
}, [['Context', '01'], ['Permission', '02'], ['Memory', '03'], ['Feedback', '04'], ['Escalation', '05'], ['Human judgment', '06']].map(([name, n]) => /*#__PURE__*/React.createElement("div", {
  key: name,
  className: "protocol-chip"
}, /*#__PURE__*/React.createElement("div", {
  className: "num"
}, n), /*#__PURE__*/React.createElement("div", {
  className: "name"
}, name)))), /*#__PURE__*/React.createElement("p", null, "This is the deeper shift. AI agents do not remove the need for organizational design. ", /*#__PURE__*/React.createElement("strong", null, "They make organizational design unavoidable.")), /*#__PURE__*/React.createElement("p", null, "The same clarity that helps an agent work well also helps a human work well. If a mission is clear enough for an agent to support, it is clearer for a new contributor too. If a decision right is explicit enough for an agent, it is easier for the team to trust. If purpose is operational enough to guide an agent, it is finally useful to humans as more than a sentence on a wall."), /*#__PURE__*/React.createElement(PullQuote, null, "AI agents make visible the ", /*#__PURE__*/React.createElement("em", null, "organizational design debt"), " we have been carrying for decades."), /*#__PURE__*/React.createElement("p", null, "Designing for agents may force us to design better for humans.")), /*#__PURE__*/React.createElement(WashRule, {
  image: ART.ribbons,
  tall: true,
  from: "paper",
  to: "parchment"
}), /*#__PURE__*/React.createElement(Section, {
  n: "03 \xB7 The collaboration gap",
  q: "Why do better tools still fail to create <em>better collaboration?</em>"
}, /*#__PURE__*/React.createElement("p", null, "We can now communicate instantly across the planet. We can gather brilliant people into a call in days. We can generate documents, code, strategies, images, research, and plans at astonishing speed."), /*#__PURE__*/React.createElement("p", null, "And still, collaboration remains strangely difficult."), /*#__PURE__*/React.createElement("p", {
  className: "lead"
}, "Turning interest into trust is hard. Turning trust into commitment is harder. Turning commitment into ", /*#__PURE__*/React.createElement("em", null, "sustained action"), " is harder still."), /*#__PURE__*/React.createElement("p", null, "This is the paradox of our time:"), /*#__PURE__*/React.createElement(PullQuote, null, "Technology scales faster than ", /*#__PURE__*/React.createElement("em", null, "coherence.")), /*#__PURE__*/React.createElement("p", null, "AI amplifies individual capability. One person with the right tools can do what once required a team. But no AI tool can replace the trust, shared purpose, mutual commitment, and living coordination needed to do complex work together."), /*#__PURE__*/React.createElement("div", {
  className: "progression"
}, /*#__PURE__*/React.createElement("div", {
  className: "progression-step"
}, /*#__PURE__*/React.createElement("div", {
  className: "meta"
}, "Abundant"), /*#__PURE__*/React.createElement("h4", null, "Communication"), /*#__PURE__*/React.createElement("p", null, "Slack, mail, calls. We have more of it than ever.")), /*#__PURE__*/React.createElement("div", {
  className: "progression-arrow"
}, "\u2192"), /*#__PURE__*/React.createElement("div", {
  className: "progression-step"
}, /*#__PURE__*/React.createElement("div", {
  className: "meta"
}, "Expensive"), /*#__PURE__*/React.createElement("h4", null, "Coordination"), /*#__PURE__*/React.createElement("p", null, "Still hand-rolled, project by project.")), /*#__PURE__*/React.createElement("div", {
  className: "progression-arrow"
}, "\u2192"), /*#__PURE__*/React.createElement("div", {
  className: "progression-step target"
}, /*#__PURE__*/React.createElement("div", {
  className: "meta"
}, "Missing"), /*#__PURE__*/React.createElement("h4", null, "Coherence"), /*#__PURE__*/React.createElement("p", null, "The shared grammar across humans and agents."))), /*#__PURE__*/React.createElement("p", null, "The missing layer is not another app. It is a shared grammar for collaboration. ", /*#__PURE__*/React.createElement("strong", null, "Audax OS exists to help build that grammar"), " for the age of humans and agents.")), /*#__PURE__*/React.createElement(WashRule, {
  image: ART.crest,
  from: "parchment",
  to: "paper"
}), /*#__PURE__*/React.createElement(Section, {
  n: "04 \xB7 Open OS, not product",
  q: "Why should this be an <em>open OS</em>, not a platform?",
  bg: "var(--surface-paper)",
  narrow: true
}, /*#__PURE__*/React.createElement("p", null, "No single platform should own the organizational OS of the agentic age."), /*#__PURE__*/React.createElement("p", null, "Audax OS is not being designed as one closed product that every organization must adopt. The ambition is different."), /*#__PURE__*/React.createElement("p", {
  className: "lead"
}, "Audax OS should become a ", /*#__PURE__*/React.createElement("em", null, "shared operating system"), ": a language, architecture, and set of principles that many people can build with."), /*#__PURE__*/React.createElement("ul", {
  style: {
    listStyle: 'none',
    padding: 0,
    margin: '24px 0 32px'
  }
}, ['Organization designers can use it.', 'AI builders can extend it.', 'Software vendors can implement it.', 'Consultancies can develop practices around it.', 'Communities can adapt it.', 'Organizations can test it.', 'Researchers can challenge it.'].map(x => /*#__PURE__*/React.createElement("li", {
  key: x,
  style: {
    padding: '12px 0',
    borderBottom: '1px solid var(--border-2)',
    fontSize: 17,
    fontWeight: 400,
    color: 'var(--ink-800)'
  }
}, x))), /*#__PURE__*/React.createElement("p", null, "Like Agile, it should not belong to one company. It should become a common grammar for a field that is still forming. ", /*#__PURE__*/React.createElement("strong", null, "The question is too important to trap inside one product roadmap.")), /*#__PURE__*/React.createElement(PullQuote, null, "The goal is ", /*#__PURE__*/React.createElement("em", null, "interoperability"), ", not capture."), /*#__PURE__*/React.createElement("p", {
  style: {
    marginTop: 32,
    fontSize: 14,
    color: 'var(--ink-500)',
    fontWeight: 300,
    lineHeight: 1.6
  }
}, "Audax OS should be: open enough to invite many contributors \xB7 structured enough to be useful \xB7 practical enough to implement \xB7 flexible enough to adapt \xB7 principled enough to protect human agency \xB7 technical enough for agentic systems \xB7 humane enough for real people.")), /*#__PURE__*/React.createElement("section", {
  className: "cta-band",
  style: {
    '--cta-image': `url(${NODE_FIELD_BG})`
  }
}, /*#__PURE__*/React.createElement("div", {
  className: "wash"
}), /*#__PURE__*/React.createElement("div", {
  className: "cta-band-inner"
}, /*#__PURE__*/React.createElement(Eyebrow, {
  color: "var(--lichen-300)"
}, "05 \xB7 Invitation"), /*#__PURE__*/React.createElement("h2", null, "Will you help shape the", /*#__PURE__*/React.createElement("br", null), "next ", /*#__PURE__*/React.createElement("em", null, "organizational OS?")), /*#__PURE__*/React.createElement("p", {
  style: {
    maxWidth: 600
  }
}, "We are inviting organization designers, agentic AI builders, collaboration infrastructure makers, regenerative practitioners, future-of-work thinkers, and serious operators to join the founding dialogue."), /*#__PURE__*/React.createElement("p", {
  style: {
    fontFamily: 'var(--font-display)',
    fontSize: 'clamp(20px, 2vw, 28px)',
    fontStyle: 'italic',
    letterSpacing: '-0.015em',
    color: 'var(--lichen-300)',
    maxWidth: 720,
    margin: '0 auto 32px',
    lineHeight: 1.3
  }
}, "What organizational operating system is worthy of humans and AI agents working together?"), /*#__PURE__*/React.createElement("p", {
  style: {
    marginBottom: 40,
    color: 'rgba(255,255,255,0.7)'
  }
}, "We are not looking for spectators. We are looking for people carrying pieces of the answer."), /*#__PURE__*/React.createElement("div", {
  style: {
    display: 'flex',
    gap: 12,
    justifyContent: 'center',
    flexWrap: 'wrap'
  }
}, /*#__PURE__*/React.createElement(Button, {
  variant: "join",
  onClick: () => window.open(JOIN_URL, '_blank'),
  icon: "arrow-right"
}, "Join to co-create"), /*#__PURE__*/React.createElement(Button, {
  variant: "ghost",
  onClick: () => onNav('spheres')
}, "Explore the Spheres")))));
window.PageWhy = PageWhy;