/* Generated from page-build.jsx by tools/build.py. Edit the .jsx file and rebuild; do not edit this file. */
/* Audax OS site · Let's Build the OS page
   The invitation to co-create: organization designers, AI builders,
   operators, and ecosystem actors helping shape the OS itself. */

const HERO_BUILD = 'assets/backgrounds/The_Gathering_httpss.mj.runLwdlSY4QCLA_abstract_horizontal_in_4a2611be-ea74-45f7-96c4-c3168455b410_3.webp';
const BUILD_AUDIENCES = [{
  n: '01',
  name: 'Organization Designers',
  q: 'Are you designing how humans work together?',
  who: 'People who design how teams, companies, networks and institutions actually work - governance, roles, decision-making, culture, trust, facilitation, learning, power and structure.',
  bring: ['team agreements', 'governance patterns', 'decision protocols', 'conflict pathways', 'culture diagnostics', 'trust infrastructure', 'organizational health maps'],
  invite: 'If you have spent years trying to make organizations more human, more adaptive, more honest, or more alive, Audax OS needs your scar tissue and your imagination.'
}, {
  n: '02',
  name: 'Agentic AI Builders',
  q: 'Are you building agents that need better organizations to live inside?',
  who: 'People building AI agents, agent platforms, AI-native tools, workflow automations, knowledge systems and human-agent interfaces.',
  bring: ['agent role cards', 'permission profiles', 'agent-ready mission canvases', 'context packets', 'escalation rules', 'inter-agent handoff protocols', 'inspectable autonomy models'],
  invite: 'If you are building agents and keep finding that the hardest problem is not the model, but the messy organization around it, you are exactly in the problem space of Audax OS.'
}, {
  n: '03',
  name: 'Collaboration Infrastructure Builders',
  q: 'Are you building the tools collective work now depends on?',
  who: 'People building tools for coordination, knowledge, governance, communication, contribution and distributed work - the plumbing of collective intelligence.',
  bring: ['shared work ontologies', 'commitment ledgers', 'portable contributor profiles', 'open protocols', 'tool interoperability models', 'human-agent collaboration interfaces'],
  invite: 'If you are building the pipes, rooms, ledgers, maps, dashboards, agents, or rituals through which modern collaboration happens, Audax OS is an invitation to make the pieces speak to each other.'
}, {
  n: '04',
  name: 'Regenerative Practitioners',
  q: 'Are you working to make organizations more alive?',
  who: 'People working with living systems, teal and turquoise organizations, developmental culture, regenerative leadership and ecological ways of organizing.',
  bring: ['living systems principles', 'developmental pathways', 'relational rituals', 'regenerative diagnostics', 'purpose practices', 'consent and care protocols', 'culture and maturity maps'],
  invite: 'If your work sits at the edge of organizational design, human development, living systems and regeneration, Audax OS needs your depth. Otherwise the future becomes a spreadsheet with wings.'
}, {
  n: '05',
  name: 'Future-of-Work Operators',
  q: 'Are you already living the problem?',
  who: 'People running distributed teams, AI-native startups, fractional organizations, communities, DAOs, venture studios and ecosystem initiatives.',
  bring: ['real use cases', 'failure stories', 'adoption pathways', 'minimum viable protocols', 'practical diagnostics', 'operational constraints', 'what must stay simple'],
  invite: 'If you are already trying to run an organization that does not fit the old model, Audax OS is a place to turn the pain into pattern.'
}, {
  n: '06',
  name: 'Governance Designers',
  q: 'Are you designing how decisions and accountability work?',
  who: 'People designing decision systems, consent processes, contribution models, DAO governance, legal structures, accountability systems and agent permission models.',
  bring: ['governance frameworks', 'decision architectures', 'accountability models', 'permission systems', 'agent governance patterns', 'consent protocols'],
  invite: 'If you have been building trustworthy systems for collective decision-making, Audax OS needs governance intelligence at its core.'
}, {
  n: '07',
  name: 'Ecosystem Weavers',
  q: 'Are you helping many centers act together?',
  who: 'People who help independent actors discover alignment, form trust, coordinate missions and learn together without central control.',
  bring: ['ecosystem mapping', 'trust and reputation signals', 'partnership protocols', 'open mission frameworks', 'contribution pathways', 'collective intelligence practices'],
  invite: 'If you understand the art of making many centers act together without forcing them into one container, you are building the outer layer of Audax OS.'
}];
const BUILD_PATHWAYS = [{
  n: '01',
  title: 'Join the Dialogue',
  body: 'Participate in conversations about the organizational OS needed for the agentic age. Bring questions, challenges and half-formed ideas.'
}, {
  n: '02',
  title: 'Bring a Use Case',
  body: 'Share a real organizational challenge involving distributed work, fractional contribution, human-agent collaboration, or ecosystem coordination.'
}, {
  n: '03',
  title: 'Contribute to the OS',
  body: 'Help refine the Spheres, Layers, Modes, principles, protocols, diagnostics and language.'
}, {
  n: '04',
  title: 'Build an Implementation',
  body: 'Create tools, agents, interfaces, templates, workshops, or integrations based on Audax OS concepts.'
}, {
  n: '05',
  title: 'Host a Conversation',
  body: 'Bring together organization designers, AI builders, operators, or ecosystem actors to explore the problem space.'
}, {
  n: '06',
  title: 'Become a Living Lab',
  body: 'Use Audax OS as a lens for your own organization, team, or community and share what is learned.'
}];
const BUILD_ROLES = ['Organization designer', 'Agentic AI builder', 'Collaboration tool builder', 'Researcher', 'Regenerative practitioner', 'Founder / operator', 'Strategic partner', 'Other'];
const PageBuild = ({
  onNav
}) => {
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("section", {
    className: "hero",
    style: {
      '--hero-image': `url(${HERO_BUILD})`,
      minHeight: '92vh',
      alignItems: 'center'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "hero-wash"
  }), /*#__PURE__*/React.createElement("div", {
    className: "hero-fade"
  }), /*#__PURE__*/React.createElement("div", {
    className: "hero-vertical"
  }, /*#__PURE__*/React.createElement("span", null, "An invitation to co-creators of the OS")), /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("div", {
    className: "hero-inner",
    style: {
      maxWidth: 960
    }
  }, /*#__PURE__*/React.createElement(Eyebrow, null, "Let's build the OS"), /*#__PURE__*/React.createElement("h1", {
    className: "display lg"
  }, "Audax OS: an invitation to build the organization OS", /*#__PURE__*/React.createElement("br", null), /*#__PURE__*/React.createElement("em", null, "for a regenerative, turquoise, agentic age")), /*#__PURE__*/React.createElement("p", {
    className: "lede",
    style: {
      maxWidth: 720
    }
  }, "Audax OS is not finished. That is the point."), /*#__PURE__*/React.createElement("p", {
    className: "lede",
    style: {
      maxWidth: 720,
      marginTop: 16
    }
  }, "We have identified a problem space that is becoming impossible to ignore. We are inviting the people who can help turn the first map into shared practice."), /*#__PURE__*/React.createElement("div", {
    className: "hero-ctas",
    style: {
      marginTop: 48
    }
  }, /*#__PURE__*/React.createElement(Button, {
    size: "lg",
    variant: "join",
    icon: "arrow-right",
    onClick: () => window.open(JOIN_URL, '_blank')
  }, "Join & Build the OS"))))), /*#__PURE__*/React.createElement("section", {
    className: "section manifesto"
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "02 \xB7 The invitation"), "What are we ", /*#__PURE__*/React.createElement("em", null, "inviting people into?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "We are inviting a founding dialogue around one question:")), /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(32px, 4vw, 56px)',
      fontWeight: 400,
      letterSpacing: '-0.025em',
      lineHeight: 1.1,
      color: 'var(--ink-900)',
      textWrap: 'balance',
      maxWidth: 920,
      padding: '48px 0',
      borderTop: '2px solid var(--forest-700)',
      borderBottom: '1px solid var(--border-1)',
      margin: '24px 0 40px'
    }
  }, "What organizational operating system is worthy of ", /*#__PURE__*/React.createElement("em", {
    style: {
      color: 'var(--forest-700)',
      fontStyle: 'italic'
    }
  }, "humans and AI agents working together?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "This dialogue is not theoretical decoration. It should lead to principles, protocols, tools, language, practices, diagnostics, experiments and implementations."), /*#__PURE__*/React.createElement("p", null, "Audax OS begins with a proposed architecture: ", /*#__PURE__*/React.createElement("strong", null, "Five Spheres"), " (what every healthy organization must care for), ", /*#__PURE__*/React.createElement("strong", null, "Five Layers"), " (where those functions operate) and ", /*#__PURE__*/React.createElement("strong", null, "Three Modes"), " (how collaboration happens between humans and agents)."), /*#__PURE__*/React.createElement("p", null, "But the details still need to be shaped. What should a contribution ledger include? How should personal agents protect consent? What does trust look like in a fractional organization? How do agent-to-agent workflows remain inspectable?"), /*#__PURE__*/React.createElement("p", null, "These are not small questions. They need many kinds of intelligence: organization intelligence, technical intelligence, governance intelligence, regenerative intelligence and the quiet intelligence of people who have seen enough failed systems to recognize a real edge when they find one.")), /*#__PURE__*/React.createElement(PullQuote, null, "Audax OS is not a product looking for users. ", /*#__PURE__*/React.createElement("em", null, "It is a problem space looking for co-creators.")))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-paper)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "03 \xB7 First circle"), "Who is needed ", /*#__PURE__*/React.createElement("em", null, "at the beginning?")), /*#__PURE__*/React.createElement("p", {
    className: "lede",
    style: {
      marginBottom: 56,
      maxWidth: 760
    }
  }, "At this stage, Audax OS is primarily for people who can help develop the OS itself. The first circle is not a mass market. It is builders, designers, practitioners and thinkers who understand that the organization itself is now the design frontier."), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: 14
    }
  }, BUILD_AUDIENCES.slice(0, 4).map(a => /*#__PURE__*/React.createElement("article", {
    key: a.n,
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 16,
      padding: '28px 22px',
      display: 'flex',
      flexDirection: 'column',
      minHeight: 220
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.22em',
      color: 'var(--forest-700)',
      marginBottom: 14
    }
  }, "CIRCLE ", a.n), /*#__PURE__*/React.createElement("h4", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 20,
      fontWeight: 400,
      letterSpacing: '-0.02em',
      lineHeight: 1.05,
      color: 'var(--ink-900)',
      margin: '0 0 12px'
    }
  }, a.name), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 13,
      fontWeight: 300,
      lineHeight: 1.45,
      color: 'var(--ink-600)',
      margin: 0,
      fontStyle: 'italic'
    }
  }, a.q)))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: 14,
      marginTop: 14
    }
  }, BUILD_AUDIENCES.slice(4).map(a => /*#__PURE__*/React.createElement("article", {
    key: a.n,
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 16,
      padding: '28px 22px',
      display: 'flex',
      flexDirection: 'column',
      minHeight: 200
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.22em',
      color: 'var(--forest-700)',
      marginBottom: 14
    }
  }, "CIRCLE ", a.n), /*#__PURE__*/React.createElement("h4", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 20,
      fontWeight: 400,
      letterSpacing: '-0.02em',
      lineHeight: 1.05,
      color: 'var(--ink-900)',
      margin: '0 0 12px'
    }
  }, a.name), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 13,
      fontWeight: 300,
      lineHeight: 1.45,
      color: 'var(--ink-600)',
      margin: 0,
      fontStyle: 'italic'
    }
  }, a.q)))))), /*#__PURE__*/React.createElement(WashRule, {
    image: ART.wave,
    from: "paper",
    to: "parchment"
  }), /*#__PURE__*/React.createElement("section", {
    className: "section"
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "04\u201308 \xB7 Deep dives"), "What does each ", /*#__PURE__*/React.createElement("em", null, "first circle need?")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      flexDirection: 'column'
    }
  }, BUILD_AUDIENCES.slice(0, 5).map((a, i) => /*#__PURE__*/React.createElement("div", {
    key: a.n,
    className: "aud-row",
    style: {
      paddingTop: i === 0 ? 56 : undefined
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", null, a.n, " \xB7 First circle"), /*#__PURE__*/React.createElement("h3", null, a.name)), /*#__PURE__*/React.createElement("div", {
    className: "who-grid"
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", null, "Who you are"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 15,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-700)',
      margin: '0 0 24px'
    }
  }, a.who), /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 17,
      fontWeight: 400,
      letterSpacing: '-0.01em',
      lineHeight: 1.35,
      color: 'var(--forest-900)',
      fontStyle: 'italic',
      background: 'var(--forest-050)',
      border: '1px solid var(--forest-200)',
      borderRadius: 12,
      padding: '16px 18px',
      margin: 0
    }
  }, a.invite)), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", null, "What you might help shape"), /*#__PURE__*/React.createElement("ul", null, a.bring.map(x => /*#__PURE__*/React.createElement("li", {
    key: x
  }, x))), /*#__PURE__*/React.createElement("a", {
    href: "#",
    className: "aud-cta",
    onClick: e => {
      e.preventDefault();
      window.open(JOIN_URL, '_blank');
    }
  }, "Join & Build the OS ", /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: 16
    }
  }, "\u2192"))))))))), /*#__PURE__*/React.createElement(WashRule, {
    image: ART.spray,
    from: "parchment",
    to: "white"
  }), /*#__PURE__*/React.createElement("section", {
    className: "section manifesto",
    style: {
      paddingTop: 80,
      paddingBottom: 80
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement(PullQuote, null, "The agentic age needs organization designers, ", /*#__PURE__*/React.createElement("em", null, "not just AI engineers with admin access.")), /*#__PURE__*/React.createElement(PullQuote, null, "Agents do not only need better prompts. ", /*#__PURE__*/React.createElement("em", null, "They need better organizational habitats.")), /*#__PURE__*/React.createElement(PullQuote, null, "The next organizational OS should be interoperable, ", /*#__PURE__*/React.createElement("em", null, "not imperial.")))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-paper)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      flexDirection: 'column'
    }
  }, BUILD_AUDIENCES.slice(5).map((a, i) => /*#__PURE__*/React.createElement("div", {
    key: a.n,
    className: "aud-row",
    style: {
      paddingTop: i === 0 ? 0 : undefined
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", null, a.n, " \xB7 First circle"), /*#__PURE__*/React.createElement("h3", null, a.name)), /*#__PURE__*/React.createElement("div", {
    className: "who-grid"
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", null, "Who you are"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 15,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-700)',
      margin: '0 0 24px'
    }
  }, a.who), /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 17,
      fontWeight: 400,
      letterSpacing: '-0.01em',
      lineHeight: 1.35,
      color: 'var(--forest-900)',
      fontStyle: 'italic',
      background: 'var(--forest-050)',
      border: '1px solid var(--forest-200)',
      borderRadius: 12,
      padding: '16px 18px',
      margin: 0
    }
  }, a.invite)), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h6", null, "What you might help shape"), /*#__PURE__*/React.createElement("ul", null, a.bring.map(x => /*#__PURE__*/React.createElement("li", {
    key: x
  }, x))), /*#__PURE__*/React.createElement("a", {
    href: "#",
    className: "aud-cta",
    onClick: e => {
      e.preventDefault();
      window.open(JOIN_URL, '_blank');
    }
  }, "Join & Build the OS ", /*#__PURE__*/React.createElement("span", {
    style: {
      fontSize: 16
    }
  }, "\u2192"))))))))), /*#__PURE__*/React.createElement(WashRule, {
    image: ART.ribbons,
    flip: true,
    from: "paper",
    to: "parchment"
  }), /*#__PURE__*/React.createElement("section", {
    className: "section"
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "09 \xB7 Partners"), "Who can ", /*#__PURE__*/React.createElement("em", null, "build with Audax OS?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 48
    }
  }, /*#__PURE__*/React.createElement("p", null, "Audax OS is intended to be an open OS, not a closed product. Like Agile, it should become something many people can interpret, extend, implement, critique, teach and build upon. Strategic partners are not future customers. They are potential co-creators.")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: 24
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 18,
      padding: '36px 36px'
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)',
      margin: '0 0 16px'
    }
  }, "Partner types"), ['Organization design consultancies', 'AI agent platforms', 'Collaboration tool vendors', 'Governance and DAO platforms', 'Knowledge management tools', 'Learning and development platforms', 'Community and network platforms', 'Research labs and foundations', 'Open-source communities', 'Venture studios and funders'].map((p, i) => /*#__PURE__*/React.createElement("div", {
    key: p,
    style: {
      padding: '10px 0',
      borderBottom: '1px solid var(--border-2)',
      fontSize: 15,
      fontWeight: 400,
      color: 'var(--ink-800)',
      display: 'flex',
      gap: 12,
      alignItems: 'center'
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 9,
      color: 'var(--forest-600)',
      letterSpacing: '0.04em',
      flexShrink: 0
    }
  }, String(i + 1).padStart(2, '0')), p))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'flex',
      flexDirection: 'column',
      gap: 16
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      background: 'var(--forest-050)',
      border: '1px solid var(--forest-200)',
      borderRadius: 18,
      padding: '32px 32px'
    }
  }, /*#__PURE__*/React.createElement("h6", {
    style: {
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      color: 'var(--forest-800)',
      margin: '0 0 16px'
    }
  }, "What partners might build"), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '0 24px'
    }
  }, ['Diagnostics', 'Protocols', 'Training programs', 'Workshops', 'AI agents', 'Tool integrations', 'Standards', 'Case studies', 'Research papers', 'Pilot programs'].map(x => /*#__PURE__*/React.createElement("div", {
    key: x,
    style: {
      padding: '8px 0',
      borderBottom: '1px solid var(--forest-200)',
      fontSize: 13,
      color: 'var(--forest-900)'
    }
  }, x)))), /*#__PURE__*/React.createElement("div", {
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 18,
      padding: '32px 32px',
      flex: 1
    }
  }, /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 22,
      fontWeight: 400,
      letterSpacing: '-0.015em',
      lineHeight: 1.2,
      color: 'var(--ink-900)',
      fontStyle: 'italic',
      margin: 0
    }
  }, "\"The goal is not platform capture. The goal is shared infrastructure.\"")))), /*#__PURE__*/React.createElement(PullQuote, null, "Audax OS should become a shared grammar many builders can use, ", /*#__PURE__*/React.createElement("em", null, "not a castle one vendor owns.")))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-paper)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "10 \xB7 Ways in"), "How can people ", /*#__PURE__*/React.createElement("em", null, "help shape Audax OS?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 56
    }
  }, /*#__PURE__*/React.createElement("p", null, "There are many ways to contribute. The goal is not to make everyone contribute in the same way. The goal is to make contribution visible, useful and alive.")), /*#__PURE__*/React.createElement("div", {
    className: "join-grid"
  }, BUILD_PATHWAYS.map(p => /*#__PURE__*/React.createElement("div", {
    key: p.n,
    className: "join-card"
  }, /*#__PURE__*/React.createElement("div", {
    className: "num"
  }, p.n), /*#__PURE__*/React.createElement("h4", null, p.title), /*#__PURE__*/React.createElement("p", null, p.body)))), /*#__PURE__*/React.createElement(PullQuote, null, "The OS will become real through ", /*#__PURE__*/React.createElement("em", null, "the quality of the people and practices that gather around it.")))), /*#__PURE__*/React.createElement(WashRule, {
    image: ART.crest,
    tall: true,
    from: "paper",
    to: "parchment"
  }), /*#__PURE__*/React.createElement("section", {
    className: "section"
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "11 \xB7 Living lab"), "Where does this ", /*#__PURE__*/React.createElement("em", null, "begin in practice?")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 56,
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 20,
      padding: '56px 56px',
      alignItems: 'start'
    }
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)',
      marginBottom: 16
    }
  }, "First living lab"), /*#__PURE__*/React.createElement("h3", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 'clamp(28px, 3vw, 40px)',
      fontWeight: 400,
      letterSpacing: '-0.02em',
      lineHeight: 1.05,
      color: 'var(--ink-900)',
      margin: '0 0 24px'
    }
  }, "The Coherence Company"), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 16,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-700)',
      margin: '0 0 16px'
    }
  }, "The Coherence Company is the first organization joining to develop, test and evolve Audax OS in real organizational life."), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 16,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-700)',
      margin: '0 0 16px'
    }
  }, "It is not the owner of the OS. It is the first living lab - using Audax OS to explore how a distributed, fractional, AI-native organization can organize work, contribution, learning, communication, human relationship and agentic collaboration."), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 16,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-700)',
      margin: 0
    }
  }, "The future organizational OS cannot be designed from a balcony. It must be tested inside real commitments, real tensions, real people, real agents, real projects and real learning loops.")), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.22em',
      textTransform: 'uppercase',
      color: 'var(--ink-500)',
      marginBottom: 16
    }
  }, "The constellation grows"), /*#__PURE__*/React.createElement("div", {
    style: {
      background: 'var(--forest-050)',
      border: '1px solid var(--forest-200)',
      borderRadius: 16,
      padding: '28px 28px',
      marginBottom: 16
    }
  }, /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 18,
      fontWeight: 400,
      letterSpacing: '-0.01em',
      lineHeight: 1.3,
      color: 'var(--forest-900)',
      fontStyle: 'italic',
      margin: 0
    }
  }, "\"The first living lab is not the owner of the field. It is the first place where the OS learns from reality.\"")), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 14,
      fontWeight: 300,
      lineHeight: 1.6,
      color: 'var(--ink-600)',
      margin: 0
    }
  }, "The Coherence Company will help generate the first practical patterns, but the OS should grow through a wider field of contributors, partners and living labs. One node in a growing constellation - not the whole sky."))))), /*#__PURE__*/React.createElement("section", {
    className: "section manifesto"
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "12 \xB7 Culture"), "What kind of conversation ", /*#__PURE__*/React.createElement("em", null, "are we trying to host?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760
    }
  }, /*#__PURE__*/React.createElement("p", null, "The founding dialogue should be serious, generous, practical and alive."), /*#__PURE__*/React.createElement("p", null, "Not a panel series where everyone performs insight and nothing changes. Not a Discord swamp where good ideas go to slowly become scroll sediment. Not a closed expert committee pretending the future has already been decided."), /*#__PURE__*/React.createElement("p", {
    className: "lead"
  }, "We want conversations that ", /*#__PURE__*/React.createElement("em", null, "move.")), /*#__PURE__*/React.createElement("p", null, "From question to pattern. From pattern to protocol. From protocol to test. From test to learning. From learning to better questions."), /*#__PURE__*/React.createElement("p", null, "The dialogue should welcome disagreement. Audax OS will be stronger if people challenge the language, test the assumptions, expose blind spots, bring edge cases and refuse lazy consensus."), /*#__PURE__*/React.createElement("p", null, /*#__PURE__*/React.createElement("strong", null, "Co-creation is not polite agreement. It is disciplined imagination."))), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2, 1fr)',
      gap: '0 64px',
      margin: '48px 0 0'
    }
  }, ['Start from real problems.', 'Stay close to practice.', 'Make concepts legible.', 'Name tensions early.', 'Protect human agency.', 'Respect technical reality.', 'Prefer protocols over slogans.', 'Treat critique as contribution.', 'Build with enough openness that others can extend it.', 'Keep asking what this makes possible for people, teams and ecosystems.'].map((p, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    style: {
      padding: '22px 0',
      borderBottom: '1px solid var(--border-2)',
      display: 'flex',
      gap: 20,
      alignItems: 'flex-start'
    }
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 11,
      fontWeight: 500,
      letterSpacing: '0.04em',
      color: 'var(--forest-700)',
      flexShrink: 0,
      minWidth: 28,
      paddingTop: 2
    }
  }, String(i + 1).padStart(2, '0')), /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 18,
      fontWeight: 400,
      letterSpacing: '-0.01em',
      color: 'var(--ink-900)',
      lineHeight: 1.25
    }
  }, p)))), /*#__PURE__*/React.createElement(PullQuote, null, "We are not gathering to admire complexity. ", /*#__PURE__*/React.createElement("em", null, "We are gathering to make it workable.")))), /*#__PURE__*/React.createElement(WashRule, {
    image: ART.spray,
    from: "white",
    to: "paper"
  }), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--surface-paper)'
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "container"
  }, /*#__PURE__*/React.createElement("h1", {
    className: "q-h1"
  }, /*#__PURE__*/React.createElement("span", {
    className: "num"
  }, "13 \xB7 Horizon"), "What could this become ", /*#__PURE__*/React.createElement("em", null, "if we build it well?")), /*#__PURE__*/React.createElement("div", {
    className: "q-body",
    style: {
      maxWidth: 760,
      marginBottom: 48
    }
  }, /*#__PURE__*/React.createElement("p", null, "If Audax OS works, it will not become one company's proprietary method. It will become a shared language for designing organizations in the agentic age.")), /*#__PURE__*/React.createElement("div", {
    style: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr 1fr',
      gap: 14
    }
  }, [{
    for: 'Organization designers',
    becomes: 'A way to speak with AI builders around shared organizational objects.'
  }, {
    for: 'Founders',
    becomes: 'A way to think beyond roles and task boards from the beginning.'
  }, {
    for: 'Contributors',
    becomes: 'A way to see commitments, value, learning and agency across contexts.'
  }, {
    for: 'Teams',
    becomes: 'A way to make work legible without becoming bureaucratic.'
  }, {
    for: 'Agents',
    becomes: 'A way to participate with context, permissions, feedback and clear boundaries.'
  }, {
    for: 'Vendors',
    becomes: 'A way to build interoperable tools around shared organizational objects.'
  }, {
    for: 'Ecosystems',
    becomes: 'A way to coordinate missions without central control.'
  }, {
    for: 'The future of work',
    becomes: 'A way to become more humane, not merely more automated.'
  }, {
    for: 'Many builders',
    becomes: 'A shared grammar many systems may one day use.'
  }].map((c, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    style: {
      background: 'var(--surface-white)',
      border: '1px solid var(--border-1)',
      borderRadius: 14,
      padding: '24px 22px'
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      fontFamily: 'var(--font-mono)',
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: '0.18em',
      textTransform: 'uppercase',
      color: 'var(--forest-700)',
      marginBottom: 10
    }
  }, "For ", c.for), /*#__PURE__*/React.createElement("p", {
    style: {
      fontFamily: 'var(--font-display)',
      fontSize: 17,
      fontWeight: 400,
      letterSpacing: '-0.01em',
      lineHeight: 1.25,
      color: 'var(--ink-900)',
      margin: 0,
      fontStyle: 'italic'
    }
  }, c.becomes)))), /*#__PURE__*/React.createElement(PullQuote, null, "Audax OS will be valuable only if it becomes ", /*#__PURE__*/React.createElement("em", null, "bigger than the people who started it.")))), /*#__PURE__*/React.createElement("section", {
    className: "section",
    style: {
      background: 'var(--bg-deep)',
      color: '#fff',
      position: 'relative',
      overflow: 'hidden'
    }
  }, /*#__PURE__*/React.createElement("div", {
    style: {
      position: 'absolute',
      inset: 0,
      background: 'var(--grad-deep)',
      opacity: 1,
      pointerEvents: 'none'
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "container-narrow",
    style: {
      position: 'relative',
      zIndex: 2,
      textAlign: 'center'
    }
  }, /*#__PURE__*/React.createElement(Eyebrow, {
    color: "var(--lichen-300)"
  }, "A closing statement"), /*#__PURE__*/React.createElement("h2", {
    className: "display",
    style: {
      color: '#fff',
      fontSize: 'clamp(40px, 5vw, 72px)',
      marginBottom: 32
    }
  }, "The old organizational OS is ", /*#__PURE__*/React.createElement("em", null, "creaking.")), /*#__PURE__*/React.createElement("p", {
    style: {
      fontSize: 19,
      fontWeight: 300,
      lineHeight: 1.55,
      color: 'rgba(255,255,255,0.78)',
      maxWidth: 620,
      margin: '0 auto 40px'
    }
  }, "The agentic age will not wait for perfect theory. We need to build the next OS through practice, dialogue and serious experimentation."), /*#__PURE__*/React.createElement(Button, {
    size: "lg",
    variant: "join",
    icon: "arrow-right",
    onClick: () => window.open(JOIN_URL, '_blank')
  }, "Let's build a holistic organization OS for our times"))));
};
window.PageBuild = PageBuild;