#!/usr/bin/env python3
"""Build the fast production site from the editable source.

    python tools/build.py

Editing stays as it always was: change the .jsx files and open dev.html, which compiles
them in the browser. Before publishing, run this script. It:

  1. compiles every .jsx file listed in dev.html into built/*.js (a browser tab opens for a
     few seconds; that tab runs the same Babel the site used to run for every visitor),
  2. writes index.html from dev.html, loading built/*.js and the production builds of
     React instead of Babel and the development builds.

Needs only Python 3 and a browser. Commit dev.html, index.html, the .jsx files and built/.
Bump the ?v=N numbers in dev.html (not index.html) before building; the build carries
them over.
"""
import base64, hashlib, http.server, os, re, socketserver, sys, threading, time, urllib.request, webbrowser

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DIST = os.path.join(ROOT, "built")
PORT = int(os.environ.get("BUILD_PORT", "8765"))
REACT = "18.3.1"
PROD = {
    "react.development.js": f"https://unpkg.com/react@{REACT}/umd/react.production.min.js",
    "react-dom.development.js": f"https://unpkg.com/react-dom@{REACT}/umd/react-dom.production.min.js",
}

saved, state = set(), {"done": False, "error": None}


def sri(url):
    data = urllib.request.urlopen(url, timeout=30).read()
    return "sha384-" + base64.b64encode(hashlib.sha384(data).digest()).decode()


class Server(socketserver.ThreadingTCPServer):
    daemon_threads = True      # never wait on a browser connection that stays open
    block_on_close = False


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **k):
        super().__init__(*a, directory=ROOT, **k)

    def log_message(self, *a):
        pass

    def do_POST(self):
        path, _, query = self.path.partition("?")
        params = dict(p.split("=", 1) for p in query.split("&") if "=" in p)
        n = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(n)
        if path == "/__save":
            name = urllib.request.unquote(params.get("name", ""))
            if not re.fullmatch(r"[A-Za-z0-9._-]+\.js", name):
                return self.send_error(400, "bad name")
            os.makedirs(DIST, exist_ok=True)
            with open(os.path.join(DIST, name), "wb") as f:
                f.write(body)
            saved.add(name)
        elif path == "/__done":
            if "error" in params:
                state["error"] = urllib.request.unquote(params["error"])
            state["done"] = True
        else:
            return self.send_error(404)
        self.send_response(204)
        self.end_headers()


def make_index():
    with open(os.path.join(ROOT, "dev.html"), newline="", encoding="utf-8") as f:
        html = f.read()
    for dev_name, url in PROD.items():
        pat = re.compile(r'<script src="https://unpkg\.com/[^"]*' + re.escape(dev_name) + r'"[^>]*></script>')
        if not pat.search(html):
            raise SystemExit("dev.html has no script tag for " + dev_name)
        html = pat.sub(f'<script src="{url}" integrity="{sri(url)}" crossorigin="anonymous"></script>', html)
    html, n = re.subn(r'[ \t]*<script src="https://unpkg\.com/@babel/standalone[^"]*"[^>]*></script>\r?\n', "", html)
    if n != 1:
        raise SystemExit("expected one Babel script tag in dev.html, found %d" % n)
    html, count = re.subn(r'<script type="text/babel" src="([^"?]+)\.jsx(\?[^"]*)?"></script>',
                          lambda m: '<script src="built/%s.js%s"></script>' % (m.group(1), m.group(2) or ""), html)
    nl = "\r\n" if "\r\n" in html else "\n"
    note = ("<!-- GENERATED by tools/build.py from dev.html. Edit dev.html and the .jsx files, "
            "then run: python tools/build.py -->" + nl)
    html = re.sub(r"(<!doctype html>\r?\n)", lambda m: m.group(1) + note, html, count=1, flags=re.I)
    with open(os.path.join(ROOT, "index.html"), "w", newline="", encoding="utf-8") as f:
        f.write(html)
    return count


def main():
    with open(os.path.join(ROOT, "dev.html"), encoding="utf-8") as f:
        expected = len(re.findall(r'type="text/babel"\s+src="[^"]+\.jsx', f.read()))
    socketserver.TCPServer.allow_reuse_address = True
    srv = Server(("127.0.0.1", PORT), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    url = f"http://localhost:{PORT}/tools/build.html"
    print("Compiling %d files. If no browser tab opens, open %s" % (expected, url))
    if not os.environ.get("BUILD_NO_BROWSER"):
        webbrowser.open(url)
    t0 = time.time()
    while not state["done"] and time.time() - t0 < 240:
        time.sleep(0.3)
    time.sleep(0.5)          # let the browser finish reading the last response
    if state["error"] or len(saved) != expected:
        raise SystemExit("Build failed: %s (saved %d of %d files)" % (state["error"] or "timed out", len(saved), expected))
    swapped = make_index()
    print("Compiled %d files into built/ and wrote index.html (%d script tags switched to built/)." % (len(saved), swapped))
    sys.stdout.flush()
    os._exit(0)                # the server thread is a daemon; leave without waiting for it


if __name__ == "__main__":
    sys.exit(main())
